type CatalogErrorCode =
  | "CATALOG_TERMS_REQUIRED"
  | "CATALOG_ITEM_NOT_FOUND"
  | "CATALOG_OFFERING_NOT_FOUND"
  | "CATALOG_VARIANT_NOT_FOUND"
  | "DUPLICATE_CATALOG_KEY"
  | "IDEMPOTENCY_MISMATCH"
  | "INSUFFICIENT_STOCK"
  | "INVALID_CATALOG_ITEM"
  | "INVALID_OFFERING"
  | "INVALID_ORDER"
  | "INVALID_STOCK_OPERATION"
  | "INVALID_UNIT_CONFIGURATION"
  | "OFFERING_UNAVAILABLE"
  | "ORDER_NOT_FOUND"
  | "RESERVATION_NOT_FOUND"
  | "REVISION_CONFLICT"
  | "STALE_CONFIGURATION"
  | "STOCK_COUNT_NOT_FOUND"
  | "STORE_NOT_FOUND"
  | "SERVICE_INTAKE_NOT_FOUND"
  | "SERVICE_JOB_NOT_FOUND"
  | "SERVICE_WORK_NOT_AUTHORIZED"
  | "INVALID_SERVICE_TRANSITION"
  | "SERVICE_ALLOCATION_CONFLICT"
  | "SERVICE_EVIDENCE_UNAVAILABLE"
  | "INVALID_ASSIGNEE"
  | "QUOTE_CONFLICT"
  | "PUBLIC_TOKEN_INVALID"

export class CatalogError extends Error {
  readonly code: CatalogErrorCode

  constructor(code: CatalogErrorCode, message: string) {
    super(message)
    this.name = "CatalogError"
    this.code = code
  }
}
