import { CATALOG_CATEGORY_PRESETS } from "./catalog-category-presets"

// Stable identities, not array positions or provider-generated labels.
const EMOJIS: Readonly<Record<string, string>> = {
  poultry: "🐔",
  "poultry:eggs": "🥚",
  "poultry:live-birds": "🐔",
  "poultry:dressed-poultry": "🍗",
  "poultry:hatching-eggs": "🐣",
  "animal-feed": "🌾",
  "animal-feed:poultry-feed": "🌾",
  "animal-feed:fish-feed": "🐟",
  "animal-feed:livestock-feed": "🐄",
  "animal-feed:pet-food": "🐾",
  "farm-supplies": "🚜",
  "farm-supplies:seeds": "🌱",
  "farm-supplies:fertilizers": "🌿",
  "farm-supplies:farm-tools": "🪏",
  "farm-supplies:packaging": "📦",
  "fresh-produce": "🥬",
  "fresh-produce:vegetables": "🥕",
  "fresh-produce:fruit": "🍎",
  "fresh-produce:tubers": "🥔",
  "fresh-produce:herbs": "🌿",
  groceries: "🛒",
  "groceries:grains-flour": "🌾",
  "groceries:cooking-ingredients": "🧂",
  "groceries:canned-food": "🥫",
  "groceries:snacks": "🍿",
  "drinks-water": "🥤",
  "drinks-water:drinking-water": "💧",
  "drinks-water:soft-drinks": "🥤",
  "drinks-water:juice": "🧃",
  "drinks-water:tea-coffee": "☕",
  "bakery-prepared-food": "🥖",
  "bakery-prepared-food:bread": "🍞",
  "bakery-prepared-food:cakes": "🎂",
  "bakery-prepared-food:pastries": "🥐",
  "bakery-prepared-food:ready-meals": "🍱",
  clothing: "👕",
  "clothing:womenswear": "👗",
  "clothing:menswear": "👔",
  "clothing:childrenswear": "🧒",
  "clothing:workwear": "🦺",
  "footwear-accessories": "👟",
  "footwear-accessories:shoes": "👟",
  "footwear-accessories:bags": "👜",
  "footwear-accessories:jewellery": "💍",
  "footwear-accessories:accessories": "🧢",
  "fabrics-sewing": "🧵",
  "fabrics-sewing:fabric": "🧶",
  "fabrics-sewing:thread-notions": "🧵",
  "fabrics-sewing:patterns": "📐",
  "fabrics-sewing:sewing-tools": "✂️",
  "beauty-personal-care": "🧴",
  "beauty-personal-care:hair-care": "💇",
  "beauty-personal-care:skin-care": "🧴",
  "beauty-personal-care:cosmetics": "💄",
  "beauty-personal-care:personal-hygiene": "🧼",
  "health-wellness": "🩺",
  "health-wellness:health-supplies": "🩺",
  "health-wellness:wellness-products": "🌿",
  "health-wellness:first-aid": "🩹",
  "health-wellness:medical-equipment": "🦽",
  electronics: "📱",
  "electronics:phones": "📱",
  "electronics:computers": "💻",
  "electronics:accessories": "🎧",
  "electronics:appliances": "🔌",
  "hardware-building": "🔨",
  "hardware-building:hand-tools": "🔨",
  "hardware-building:electrical-supplies": "💡",
  "hardware-building:plumbing-supplies": "🚰",
  "hardware-building:building-materials": "🧱",
  "home-household": "🏠",
  "home-household:cleaning-supplies": "🧹",
  "home-household:kitchenware": "🍳",
  "home-household:home-textiles": "🛏️",
  "home-household:furniture": "🪑",
  "spare-parts": "⚙️",
  "spare-parts:vehicle-parts": "🚗",
  "spare-parts:appliance-parts": "🔌",
  "spare-parts:phone-parts": "📱",
  "spare-parts:machine-parts": "⚙️",
  "tailoring-services": "✂️",
  "tailoring-services:custom-sewing": "🪡",
  "tailoring-services:alterations": "📏",
  "tailoring-services:repairs": "🧵",
  "tailoring-services:embroidery": "🌸",
  "beauty-services": "💇",
  "beauty-services:hair-services": "💇",
  "beauty-services:nail-services": "💅",
  "beauty-services:skin-treatments": "🧴",
  "beauty-services:spa-treatments": "🧖",
  "clothing-care": "🧺",
  "clothing-care:laundry": "🧺",
  "clothing-care:dry-cleaning": "👔",
  "clothing-care:ironing": "♨️",
  "clothing-care:specialist-cleaning": "🧼",
  "repair-services": "🔧",
  "repair-services:phone-repairs": "📱",
  "repair-services:appliance-repairs": "🔌",
  "repair-services:vehicle-servicing": "🚗",
  "repair-services:property-maintenance": "🏠",
  "food-services": "🍽️",
  "food-services:catering": "🍽️",
  "food-services:meal-preparation": "🍱",
  "food-services:event-service": "🎉",
  "food-services:baking-services": "🧁",
  "professional-services": "💼",
  "professional-services:consulting": "💬",
  "professional-services:design": "🎨",
  "professional-services:training": "🎓",
  "professional-services:administrative-services": "📋",
}

export function catalogCategoryEmoji(key?: string | null) {
  return EMOJIS[key?.replace(/^preset:/, "") ?? ""] ?? "🏷️"
}

export function catalogCategoryLabelEmoji(label: string) {
  const normalized = label.trim().toLowerCase()
  for (const root of CATALOG_CATEGORY_PRESETS) {
    if (root.label.toLowerCase() === normalized)
      return catalogCategoryEmoji(root.key)
    for (const child of root.subcategories) {
      if (`${root.label} / ${child.label}`.toLowerCase() === normalized)
        return catalogCategoryEmoji(child.key)
    }
  }
  return "🏷️"
}
