import { createRoot } from "react-dom/client"
import { QueryClient,QueryClientProvider } from "@tanstack/react-query"
import { createTRPCClient } from "@trpc/client"
import { observable } from "../../apps/api/node_modules/@trpc/server/dist/observable/index.mjs"
import { NuqsAdapter } from "nuqs/adapters/react"
import type { AppRouter } from "@ewatrade/api/trpc/routers/_app"
import { TRPCProvider } from "../../apps/dashboard/src/trpc/client"
import { CustomerLedgerStatement } from "../../apps/dashboard/src/components/customer-ledger/customer-ledger-statement"
import { CustomerLedgerSheet } from "../../apps/dashboard/src/components/sheets/customer-ledger-sheet"
import { useState } from "react"
const date=new Date("2026-10-02T10:00:00.000Z")
let debit=0n,credit=0n
const entries=Array.from({length:35},(_,i)=>{const side=i===0||i>1&&i%2===0?"DEBIT":"CREDIT";const amountMinor=i===0?"2400000":i===1?"600000":"100";if(side==="DEBIT")debit+=BigInt(amountMinor);else credit+=BigInt(amountMinor);return {id:`fixture-entry-${i+1}`,sequence:String(i+1),kind:i===0?"OPENING_DEBT":i===1?"RECEIPT":"REVERSAL",side,amountMinor,sourceKind:i===0?"CUSTOMER_OPENING":i===1?"CUSTOMER_RECEIPT":"CORRECTION",sourceId:`fixture-source-${i+1}`,orderId:null,storeId:null,actorUserId:"fixture-owner",reversalOfId:i>1?`fixture-old-${i}`:null,effectiveAt:date,recordedAt:date,description:i===0?"Opening debt":i===1?"Customer cash received":`Retained correction sample ${i+1}`,runningBalanceMinor:(debit-credit).toString()}})
const totals={debitMinor:debit.toString(),creditMinor:credit.toString(),allocatedMinor:"0",outstandingDebtMinor:debit.toString(),availableCreditMinor:credit.toString(),netBalanceMinor:(debit-credit).toString()}
const account={id:"fixture-account",customer:{id:"fixture-customer",name:"Amina Stores (sample)",email:null,phone:null},currencyCode:"NGN",revision:"35",snapshotSequence:"35",book:{id:"fixture-book",currencyCode:"NGN",startsAt:new Date("2026-10-01")},totals,coverage:"POSTED_CUSTOMER_LEDGER_ENTRIES",completeness:"INCOMPLETE_SOURCE_COVERAGE"}
const money=(id:string,purpose:string)=>({id,bookId:"fixture-book",code:id,name:id,kind:"ASSET",purpose,archivedAt:null,createdAt:date,debitMinor:"0",creditMinor:"0",balanceMinor:"0"})
const allocation={id:"fixture-allocation",sequence:"3",amountMinor:"50000",releasedAmountMinor:"50000",remainingAmountMinor:"0",actorUserId:"fixture-owner",createdAt:date,creditEntryId:entries[1]?.id,chargeEntryId:entries[0]?.id,credit:entries[1],charge:entries[0]}
const client=createTRPCClient<AppRouter>({links:[()=>({op})=>observable(observer=>{let data:unknown;const input=op.input as Record<string,unknown>;try{if(op.type!=="query")throw new Error("Read-only browser fixture: financial writes are disabled.");if(op.path==="customerLedger.accountDetail")data=account;else if(op.path==="customerLedger.statement"){const after=Number(input.afterSequence??0),limit=Number(input.limit??30);const page=entries.filter(e=>Number(e.sequence)>after).slice(0,limit);data={accountId:account.id,customerId:account.customer.id,currencyCode:"NGN",currentRevision:"35",snapshotSequence:String(input.snapshotSequence??35),coverage:account.coverage,completeness:account.completeness,totals,entries:page,nextCursor:after+limit<35?page.at(-1)?.sequence:null}}else if(op.path==="customerLedger.sources"){const e=entries[input.side==="CREDIT"?1:0];data={accountId:account.id,currentRevision:"35",snapshotSequence:"35",sources:[{...e,usedAmountMinor:"0",remainingAmountMinor:e?.amountMinor,order:null}],nextCursor:null}}else if(op.path==="finance.balances")data={currencyCode:"NGN",snapshotSequence:"35",startsAt:date,accounts:[money("Shop cash","CASH"),money("Business bank","BANK")]};else if(op.path==="customerLedger.entryDetail"){const e=entries.find(e=>e.id===input.entryId)??entries[0];data={accountId:account.id,customerId:account.customer.id,currencyCode:"NGN",currentRevision:"35",snapshotSequence:"35",entry:e,receipt:e?.kind==="RECEIPT"?{id:"fixture-receipt",moneyAccountId:"Shop cash",method:"CASH",reference:null}:null,reversal:null,usedAmountMinor:"0",remainingAmountMinor:e?.amountMinor,reconciliationRequired:false,allocations:e?.sequence==="1"||e?.sequence==="2"?[allocation]:[],nextCursor:null}}else if(op.path==="customerLedger.allocationHistory")data={accountId:account.id,currencyCode:"NGN",currentRevision:"35",allocation,releasedAmountMinor:"50000",remainingAmountMinor:"0",reconciliationRequired:false,releases:[{id:"fixture-release-1",sequence:"4",amountMinor:"25000",reason:"Correct partial application",actorUserId:"fixture-owner",createdAt:date,orderSettlementReversal:null},{id:"fixture-release-2",sequence:"5",amountMinor:"25000",reason:"Release remaining application",actorUserId:"fixture-admin",createdAt:date,orderSettlementReversal:null}],nextCursor:null,coverage:account.coverage,completeness:account.completeness};else if(op.path==="customerLedger.commandStatus")data={status:"NOT_FOUND"};else throw new Error(`Unsupported read-only fixture procedure: ${op.path}`);observer.next({result:{data}});observer.complete()}catch(error){observer.error(error as Error)}return()=>{}})]})
const queryClient=new QueryClient({defaultOptions:{queries:{retry:false}}})
function Fixture(){const [ready]=useState(true);return <QueryClientProvider client={queryClient}><TRPCProvider trpcClient={client} queryClient={queryClient}><NuqsAdapter><main className="mx-auto flex max-w-6xl flex-col gap-6 p-6"><aside className="bg-muted p-4 text-sm">Isolated browser fixture · sample data · all financial mutations disabled. Native acceptance is not inferred.</aside><h1 className="text-2xl font-medium">Amina Stores · Customer statement</h1>{ready?<CustomerLedgerStatement accountId="fixture-account"/>:null}<CustomerLedgerSheet actorUserId="fixture-owner" tenantId="fixture-tenant" customerId="fixture-customer"/></main></NuqsAdapter></TRPCProvider></QueryClientProvider>}
createRoot(document.getElementById("root")!).render(<Fixture/>);
