import { financePostingCommandId } from "./commands"
import type { ReviewedPurchaseSourceFacts } from "./reviewed-cost-purchase-facts"
import { financePayloadHash, validateFinanceLines } from "./rules"

const date = new Date("2026-09-01T12:00:00Z")
export function reviewedPurchaseFixture(): ReviewedPurchaseSourceFacts {
  const inventory = {
    id: "inventory",
    bookId: "book",
    code: "1300",
    kind: "ASSET",
    purpose: "INVENTORY",
  }
  const payable = {
    id: "payable",
    bookId: "book",
    code: "2000",
    kind: "LIABILITY",
    purpose: "PAYABLE",
  }
  const receipt = {
    id: "receipt",
    tenantId: "tenant",
    bookId: "book",
    billLineId: "line",
    stockOperationId: "operation",
    stockMovementId: "movement",
  }
  const journalHash = financePayloadHash({
    sourceKind: "PURCHASE_BILL",
    sourceId: "bill",
    description: "Purchase",
    effectiveAt: date,
    storeId: "store",
    lines: validateFinanceLines([
      { accountId: "inventory", side: "DEBIT", amountMinor: "300" },
      { accountId: "payable", side: "CREDIT", amountMinor: "300" },
    ]),
  })
  return {
    book: {
      id: "book",
      tenantId: "tenant",
      currencyCode: "NGN",
      startsAt: new Date("2026-01-01T00:00:00Z"),
      lastSequence: 1n,
    },
    through: new Date("2026-10-01T00:00:00Z"),
    receipt,
    bill: {
      id: "bill",
      bookId: "book",
      kind: "PURCHASE",
      supplierId: "supplier",
      supplierBookId: "book",
      storeId: "store",
      storeTenantId: "tenant",
      currencyCode: "NGN",
      actorUserId: "actor",
      description: "Purchase",
      incurredAt: date,
      totalMinor: 300n,
      corrected: false,
      lineCount: 2,
      originalEntryCount: 1,
      lines: [
        {
          id: "line",
          bookId: "book",
          billId: "bill",
          position: 0,
          amountMinor: 100n,
          account: inventory,
          receipt,
        },
        {
          id: "line-two",
          bookId: "book",
          billId: "bill",
          position: 1,
          amountMinor: 200n,
          account: inventory,
          receipt: {
            ...receipt,
            id: "receipt-two",
            billLineId: "line-two",
            stockOperationId: "operation-two",
            stockMovementId: "movement-two",
          },
        },
      ],
    },
    operation: {
      id: "operation",
      tenantId: "tenant",
      storeId: "store",
      type: "RECEIPT",
      source: "finance_purchase",
      actorUserId: "actor",
      effectiveAt: date,
      clientOperationId: financePostingCommandId(
        "purchase-command",
        "purchase-stock:book:0",
      ),
      payloadHash: "a".repeat(64),
      linkedOperationId: null,
      correctionOfOperationId: null,
      ownerCounts: {
        movements: 1,
        purchaseReceipts: 1,
        productFulfillments: 0,
        corrections: 0,
      },
    },
    movement: {
      id: "movement",
      operationId: "operation",
      balanceSourceId: "balance",
      balanceTenantId: "tenant",
      balanceStoreId: "store",
      currencyCode: "NGN",
      effect: "2",
      before: "0",
      after: "2",
      reversalOfMovementId: null,
    },
    event: {
      id: "event",
      tenantId: "tenant",
      bookId: "book",
      poolId: "pool",
      poolTenantId: "tenant",
      poolBookId: "book",
      poolBalanceSourceId: "balance",
      balanceSourceId: "balance",
      stockOperationId: "operation",
      stockMovementId: "movement",
      purchaseReceiptId: "receipt",
      productReturnCostId: null,
      sequence: 1n,
      kind: "PURCHASE_RECEIPT",
      sourceKind: "PURCHASE_RECEIPT",
      sourceId: "receipt",
      sourceCostMinor: 100n,
      valueBeforeMinor: 0n,
      valueDeltaMinor: 100n,
      valueAfterMinor: 100n,
      unknownReason: null,
      actorUserId: "actor",
      effectiveAt: date,
      effect: "2",
      before: "0",
      after: "2",
    },
    supplierEntry: {
      id: "supplier-entry",
      bookId: "book",
      supplierId: "supplier",
      billId: "bill",
      kind: "PURCHASE_BILL",
      side: "CREDIT",
      amountMinor: 300n,
      actorUserId: "actor",
      effectiveAt: date,
      journalEntryId: "journal",
      moneyAccountId: null,
      paymentId: null,
      reversalOfId: null,
      reversalCount: 0,
    },
    journal: {
      id: "journal",
      bookId: "book",
      sequence: 1n,
      sourceKind: "PURCHASE_BILL",
      sourceId: "bill",
      description: "Purchase",
      actorUserId: "actor",
      storeId: "store",
      effectiveAt: date,
      payloadHash: journalHash,
      reversalOfId: null,
      reversed: false,
      lines: [
        {
          id: "debit",
          bookId: "book",
          entryId: "journal",
          debitMinor: 300n,
          creditMinor: 0n,
          description: null,
          account: inventory,
        },
        {
          id: "credit",
          bookId: "book",
          entryId: "journal",
          debitMinor: 0n,
          creditMinor: 300n,
          description: null,
          account: payable,
        },
      ],
    },
    command: {
      id: "command",
      bookId: "book",
      kind: "RECORD_PURCHASE",
      clientCommandId: "purchase-command",
      actorUserId: "actor",
      payloadHash: "b".repeat(64),
      resultId: "bill",
    },
    postingCommand: {
      id: "posting-command",
      bookId: "book",
      kind: "POST_JOURNAL",
      clientCommandId: financePostingCommandId(
        "purchase-command",
        "purchase-journal",
      ),
      actorUserId: "actor",
      payloadHash: journalHash,
      entryId: "journal",
    },
  }
}
