from pathlib import Path
import importlib.util,json,subprocess,time
spec=importlib.util.spec_from_file_location('qa',Path(__file__).with_name('qa-emulator.py'))
qa=importlib.util.module_from_spec(spec);spec.loader.exec_module(qa)
qa.open_scene('stock-work','light','business-b')
results=[]
def check(name,ok):
 results.append({'check':name,'pass':ok});print(name+': '+('PASS' if ok else 'FAIL'),flush=True)
before=qa.capture('motion-01-rest')
check('Dock visible at rest',' Open create options' in before)
record=subprocess.Popen([qa.ADB,'-s',qa.DEVICE,'shell','screenrecord','--time-limit','15','/sdcard/home-motion.mp4'])
time.sleep(.7)
qa.swipe(duration=650)
down=qa.capture('motion-02-down')
check('Downward scroll hides dock from accessibility tree',' Open create options' not in down)
qa.shell('input','swipe','540','1000','540','1220','650')
up=qa.capture('motion-03-up')
check('Upward scroll reveals dock',' Open create options' in up)
for _ in range(10):qa.swipe(duration=200)
bottom=qa.capture('motion-04-bottom')
check('Bottom edge restores dock',' Open create options' in bottom)
record.wait()
qa.adb('pull','/sdcard/home-motion.mp4',str(qa.OUT/'home-motion.mp4'))
gesture=subprocess.Popen([qa.ADB,'-s',qa.DEVICE,'shell','input swipe 540 1750 540 350 3000'])
time.sleep(1.5)
(qa.OUT/'motion-05-edge-held.png').write_bytes(qa.adb('exec-out','screencap','-p'))
gesture.wait();time.sleep(.6)
qa.capture('motion-06-edge-released')
(qa.OUT/'motion-results.json').write_text(json.dumps(results,indent=2)+'\n')
