const directions={1:{name:'Quick receipt',caption:'01 / Quick receipt · focused sheet'},2:{name:'Preview & export',caption:'02 / Preview & export · full document view'},3:{name:'Receipt tray',caption:'03 / Receipt tray · compact file review'}};
const sourceOrders=[
 {id:1,ref:'ORD-0041',customer:'Amina Yusuf',total:3450000,paid:3450000,items:[{name:'Premium rice · 10 kg',qty:2,unit:1500000},{name:'Groundnut oil · 2 L',qty:1,unit:450000}]},
 {id:2,ref:'ORD-0042',customer:'Bala Ibrahim',total:1800000,paid:1800000,items:[{name:'Honey beans · 5 kg',qty:2,unit:650000},{name:'Semolina · 2 kg',qty:2,unit:250000}]},
 {id:3,ref:'ORD-0043',customer:'Zainab Bello',total:1250000,paid:750000,items:[{name:'Groundnut oil · 5 L',qty:1,unit:950000},{name:'Table salt · 1 kg',qty:3,unit:100000}]},
 {id:4,ref:'ORD-0044',customer:'Musa Ade',total:860000,paid:0,canceled:true,items:[{name:'Brown rice · 5 kg',qty:1,unit:860000}]}
];
let direction=2,surface='dashboard',scope='single';const states=new Map();let openerId='open-receipt';
const stage=document.getElementById('stage');
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=n=>'₦'+(n/100).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2});
function key(){return `${direction}/${surface}/${scope}`;}
function initial(){return {step:'orders',selected:scope==='single'?[1]:[1,2,3],format:'pdf',customer:true,payment:true,note:'Thank you for shopping with us.',index:0,scenario:'normal',failed:[],toast:'',busy:false,timer:null};}
function state(){if(!states.has(key()))states.set(key(),initial());return states.get(key());}
function icon(name){const paths={back:'M10 4l-6 6 6 6M4 10h13',next:'M7 4l6 6-6 6',close:'M5 5l10 10M15 5L5 15',file:'M6 2h7l4 4v12H3V2h3M12 2v5h5M6 11h8M6 14h6',check:'M4 10l4 4 8-8',download:'M10 2v11m-4-4 4 4 4-4M3 13v4h14v-4',search:'M13 13l5 5M14 8a6 6 0 1 1-12 0 6 6 0 0 1 12 0',grid:'M3 3h5v5H3zM12 3h5v5h-5zM3 12h5v5H3zM12 12h5v5h-5z',bag:'M3 6h14v12H3zM7 6V4a3 3 0 0 1 6 0v2'};return `<svg class="icon" viewBox="0 0 20 20" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;}
function orders(){const s=state();return sourceOrders.map(o=>{const r=structuredClone(o);if(r.id===1&&s.scenario==='partial')r.paid=2000000;if(r.id===1&&s.scenario==='unpaid')r.paid=0;if(r.id===1&&s.scenario==='long'){r.items=Array.from({length:22},(_,i)=>({name:`Pantry item ${i+1} · family pack`,qty:1,unit:150000+i*5000}));r.total=r.items.reduce((sum,i)=>sum+i.unit*i.qty,0);r.paid=r.total;}return r;});}
function selected(){return orders().filter(o=>state().selected.includes(o.id)&&!o.canceled);}
function status(o){return o.canceled?'<span class="status muted">Canceled</span>':`<span class="status ${o.paid<o.total?'warn':''}">${o.paid===o.total?'Paid':o.paid?'Part paid':'Unpaid'}</span>`;}
function receipt(o){const s=state();return `<article class="receipt" aria-label="Receipt preview for ${e(o.ref)}"><header class="receipt-head"><div class="receipt-logo">J</div><h3>Jawdah Provisions</h3><p>12 Adeola Street, Lagos<br>+234 800 000 0000</p></header><div class="receipt-title"><span>Order receipt</span><span>${o.paid===o.total?'Paid':o.paid?'Part paid':'Unpaid'}</span></div><div class="receipt-meta"><span>${e(o.ref)}</span><span>03 Oct 2026 · 10:24 AM</span></div>${s.customer?`<p class="receipt-customer">${e(o.customer)}</p>`:''}${o.items.map(i=>`<div class="receipt-item"><div><strong>${e(i.name)}</strong><small>${i.qty} × ${cash(i.unit)}</small></div><span class="money">${cash(i.unit*i.qty)}</span></div>`).join('')}<div class="receipt-totals"><div><span>Subtotal</span><span class="money">${cash(o.total)}</span></div><div class="total"><span>Order total</span><span class="money">${cash(o.total)}</span></div></div>${s.payment?`<div class="receipt-payment"><div><span>Payment received</span><span class="money">${cash(o.paid)}</span></div><div><span>Balance remaining</span><span class="money">${cash(o.total-o.paid)}</span></div></div>`:''}<footer class="receipt-note"><strong>${e(s.note||'Thank you for shopping with us.')}</strong>Keep this receipt for your records.</footer></article>`;}
function selectionLabel(){return scope==='single'?selected()[0]?.ref||'No Order':`${selected().length} receipts · one per Order`;}
function previewNav(){const list=selected(),s=state();s.index=Math.min(s.index,Math.max(0,list.length-1));const o=list[s.index];return `<div class="preview-nav"><span>${o?e(o.ref)+' · '+e(o.customer):'No Orders selected'}</span>${list.length>1?`<div><button data-action="previous" aria-label="Previous receipt" ${s.index===0?'disabled':''}>${icon('back')}</button><span>${s.index+1} / ${list.length}</span><button data-action="next" aria-label="Next receipt" ${s.index===list.length-1?'disabled':''}>${icon('next')}</button></div>`:''}</div>`;}
function formatControls(){const s=state(),group=selected().length>1;return `<div class="format-grid"><label class="format-choice"><input type="radio" name="format" value="pdf" ${s.format==='pdf'?'checked':''}><span><strong>PDF</strong><small>${group?'One PDF · one receipt per page':'For printing & sharing'}</small></span></label><label class="format-choice"><input type="radio" name="format" value="image" ${s.format==='image'?'checked':''}><span><strong>Image</strong><small>${group?'PNG per Order · ZIP download':'A clear, full-length PNG'}</small></span></label></div>`;}
function options(){const s=state();return `<section class="options" aria-label="Receipt options"><h3>File format</h3>${formatControls()}<div style="margin-top:17px"><label class="option-row"><span>Customer name</span><input type="checkbox" name="customer" ${s.customer?'checked':''}></label><label class="option-row"><span>Payment breakdown</span><input type="checkbox" name="payment" ${s.payment?'checked':''}></label></div><label class="text-label">Thank-you note<input name="note" maxlength="120" value="${e(s.note)}" placeholder="Thank you for shopping with us."></label></section>`;}
function notice(){const s=state();return s.scenario==='offline'?'<p class="notice warning">You’re offline. Connect to prepare a receipt from the latest Order details.</p>':state().selected.includes(4)?'<p class="notice warning">ORD-0044 is canceled and excluded. The other selected Orders remain ready.</p>':'';}
function sidebar(){return `<aside class="sidebar"><div class="brand"><span class="brandmark">↗</span>EwaTrade</div><div class="business-chip"><span class="business-logo">J</span><span>Jawdah<br><small class="fine">Lagos Store</small></span></div><nav aria-label="Sample application navigation"><div class="nav-item">${icon('grid')}Overview</div><div class="nav-item current">${icon('bag')}Orders</div><div class="nav-item">${icon('grid')}Catalog</div><div class="nav-item">${icon('file')}Inventory</div><div class="nav-item">${icon('file')}Customers</div></nav><div class="avatar-row"><span class="avatar">AY</span><span>Amina Yusuf<br>Owner</span></div></aside>`;}
function desktopOrders(){const s=state(),single=scope==='single',o=orders()[0];return `<div class="context" id="product-context"><div class="page-heading"><div><p class="eyebrow">${single?'Orders / '+o.ref:'Lagos Store'}</p><h2>${single?o.ref:'Orders'}</h2><p>${single?'03 October 2026 · 10:24 AM':'Your sales, payments and fulfilment.'}</p></div><button class="${single?'primary':''}" id="open-receipt" data-action="open" ${!selected().length?'disabled':''}>${icon('file')} ${single?'Receipt':'Generate receipts'}</button></div>${single?`<div class="order-card"><div style="display:flex;justify-content:space-between"><span class="fine">Order total</span>${status(o)}</div><p class="big-amount money">${cash(o.total)}</p><p class="fine" style="margin-top:9px">${e(o.customer)} · 2 items</p><div style="margin-top:20px">${o.items.slice(0,5).map(i=>`<div class="order-line"><span>${e(i.name)}<small class="fine" style="display:block">${i.qty} × ${cash(i.unit)}</small></span><span class="money">${cash(i.qty*i.unit)}</span></div>`).join('')}<div class="order-line"><span>Payment received</span><span class="money">${cash(o.paid)}</span></div><div class="order-line"><span>Balance remaining</span><span class="money">${cash(o.total-o.paid)}</span></div></div></div>`:`<div class="searchbar">${icon('search')} Search Orders</div><table class="table"><thead><tr><th><span class="fine">Select</span></th><th>Order / Customer</th><th class="item-col">Items</th><th>Total</th><th>Payment</th><th></th></tr></thead><tbody>${orders().map(o=>`<tr><td><input type="checkbox" data-pick="${o.id}" aria-label="Select ${o.ref}" ${s.selected.includes(o.id)?'checked':''}></td><td><strong>${o.ref}</strong><small>${o.customer}</small></td><td class="item-col">${o.items.length} items</td><td class="money">${cash(o.total)}</td><td>${status(o)}</td><td><button class="icon-button" data-single="${o.id}" aria-label="Receipt for ${o.ref}" ${o.canceled?'disabled':''}>${icon('file')}</button></td></tr>`).join('')}</tbody></table><div class="selection-bar"><span>${s.selected.length} selected</span><div class="toolbar-inline"><button class="quiet" data-action="deselect">Clear</button><button class="primary" data-action="open" ${!selected().length?'disabled':''}>Generate receipts</button></div></div>`}</div>`;}
function mobileOrders(){const s=state(),single=scope==='single',o=orders()[0];return `<div class="phone-status"><span>9:41</span><span>● ▰</span></div><div class="mobile-bar"><span>${icon('back')}</span><h3>${single?o.ref:'Orders'}</h3><span class="fine">${single?'':'Select'}</span></div><div class="mobile-body" id="product-context">${single?`<p class="fine">03 Oct 2026 · 10:24 AM</p><div class="order-card"><div style="display:flex;justify-content:space-between"><span class="fine">Order total</span>${status(o)}</div><p class="big-amount money">${cash(o.total)}</p><p class="fine" style="margin-top:8px">${e(o.customer)}</p></div><div class="order-card"><h3>Items</h3>${o.items.slice(0,5).map(i=>`<div class="order-line"><span>${e(i.name)}<small class="fine" style="display:block">${i.qty} × ${cash(i.unit)}</small></span><span class="money">${cash(i.unit*i.qty)}</span></div>`).join('')}</div><div class="order-card"><div class="order-line"><span>Payment received</span><strong class="money">${cash(o.paid)}</strong></div><div class="order-line"><span>Balance remaining</span><strong class="money">${cash(o.total-o.paid)}</strong></div></div>`:`<div class="page-heading"><div><h2>Select Orders</h2><p>Choose the receipts you need.</p></div></div><div class="mobile-list">${orders().map(o=>`<label class="mobile-order"><input type="checkbox" data-pick="${o.id}" aria-label="Select ${o.ref}" ${s.selected.includes(o.id)?'checked':''}><div class="grow"><strong>${o.ref}</strong><p>${o.customer}</p></div><div><p class="money" style="color:var(--ink);margin:0 0 6px">${cash(o.total)}</p>${status(o)}</div></label>`).join('')}</div>`}</div><div class="mobile-footer"><span class="fine">${single?'PDF or image':s.selected.length+' selected'}</span><button class="primary" id="open-receipt" data-action="open" ${!selected().length?'disabled':''}>${icon('file')} ${single?'Receipt':'Generate receipts'}</button></div>`;}
function header(){return `<header class="sheet-header"><div><p class="eyebrow">${scope==='single'?'Order document':'Group export'}</p><h2>Receipt${scope==='group'?'s':''}</h2><p class="fine">${selectionLabel()}</p></div><button class="icon-button" data-action="close" aria-label="Back to Orders">${icon(direction===2?'back':'close')}</button></header>`;}
function ready(){const s=state(),list=selected(),available=list.filter(o=>!s.failed.includes(o.id));return `<section class="ready-area"><div class="ready-mark">${icon('check')}</div><h2>${available.length===list.length?'Your receipt'+(list.length>1?'s are':' is')+' ready.':`${available.length} of ${list.length} receipts ready.`}</h2><p>${s.format==='pdf'?'PDF':'PNG image'}${list.length>1?' · One receipt per Order':''}</p>${s.failed.length?'<p class="notice warning" style="margin-top:16px">One receipt couldn’t be prepared. Your ready files are kept.</p>':''}<div class="manifest">${list.map(o=>`<div class="file-row"><span class="file-icon">${s.format==='pdf'?'PDF':'PNG'}</span><div class="grow"><strong>${e(o.ref)}-receipt.${s.format==='pdf'?'pdf':'png'}</strong><small>${e(o.customer)} · ${s.failed.includes(o.id)?'Preparation failed':'Ready'}</small></div>${s.failed.includes(o.id)?`<button data-retry="${o.id}">Retry</button>`:`<span class="status">${icon('check')}Ready</span>`}</div>`).join('')}</div>${list.length===1?`<div class="document-zone">${receipt(list[0])}</div>`:''}<div class="toast" role="status" aria-live="polite">${e(s.toast)}</div></section>`;}
function footer(){const s=state(),ready=s.step==='ready',noneReady=ready&&selected().every(o=>s.failed.includes(o.id));return `<footer class="sheet-footer"><button data-action="${ready?'edit':'close'}">${ready?'Edit':'Cancel'}</button><button class="primary" data-action="${ready?'download':'prepare'}" ${s.busy||s.scenario==='offline'||!selected().length||noneReady?'disabled':''}>${icon(ready?'download':'file')} ${s.busy?'Preparing…':ready?(surface==='mobile'?'Save '+(s.format==='pdf'?'PDF':selected().length>1?'images':'image'):'Download '+(s.format==='pdf'?'PDF':selected().length>1?'images':'image')):'Prepare '+(scope==='group'?'receipts':'receipt')}</button>${ready&&surface==='mobile'?`<button data-action="share" ${noneReady?'disabled':''}>Share</button>`:''}</footer>`;}
function previewBody(){const list=selected(),s=state(),o=list[s.index];if(s.step==='ready')return ready();if(!o)return '<p class="notice warning">Select an Order to prepare a receipt.</p>';return notice()+(direction===3?`<div class="tray-summary"><div class="paper-thumb">${receipt(o)}</div><div><h3>${scope==='group'?list.length+' Order receipts':o.ref+' receipt'}</h3><p>${scope==='group'?'Each Order keeps its own receipt.':e(o.customer)}</p><p>${cash(o.total)} · ${o.paid===o.total?'Paid':o.paid?'Part paid':'Unpaid'}</p><button class="quiet" data-action="expand">View full preview ${icon('next')}</button></div></div>`:previewNav()+`<div class="document-zone">${receipt(o)}</div>`)+options();}
function draw(){const s=state();document.getElementById('flow-caption').textContent='Orders → Receipt → Preview → Download';document.querySelectorAll('[data-direction]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.direction)===direction));document.querySelectorAll('[data-surface]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.surface===surface));document.querySelectorAll('[data-scope]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scope===scope));document.getElementById('scenario').value=s.scenario;document.getElementById('direction-caption').textContent=directions[direction].caption;const desktop=surface==='dashboard',open=s.step!=='orders';
 if(desktop){stage.innerHTML=`<div class="app dashboard-app">${sidebar()}<section class="app-main"><div class="topbar"><span>Jawdah Provisions / Lagos Store</span><span>Search anything <span class="avatar">AY</span></span></div>${open&&direction===2?`<div class="workspace-view">${header()}${s.step==='ready'?`<div class="sheet-content">${ready()}</div>`:`<div class="workspace-layout"><div class="workspace-preview">${notice()}${previewNav()}<div class="document-zone">${selected()[s.index]?receipt(selected()[s.index]):''}</div></div><aside class="workspace-options">${options()}<p class="fine" style="margin-top:22px">${selectionLabel()}</p></aside></div>`}${footer()}</div>`:desktopOrders()}</section>${open&&direction!==2?`<div class="preview-backdrop" data-action="close" style="position:absolute;inset:0;background:#10251c2b;z-index:3"></div><dialog class="sheet d${direction}" aria-label="Order receipt export">${header()}<div class="sheet-content">${previewBody()}</div>${footer()}</dialog>`:''}</div>`;}
 else {stage.innerHTML=`<div class="app mobile-app">${open&&direction===2?`<div class="phone-status"><span>9:41</span><span>● ▰</span></div><div class="mobile-bar"><button class="icon-button" data-action="close" aria-label="Back to Orders">${icon('back')}</button><h3>${s.step==='ready'?'Ready to save':'Receipt preview'}</h3><span style="width:42px"></span></div><div class="mobile-preview">${previewBody()}</div>${footer()}`:mobileOrders()}${open&&direction!==2?`<div class="preview-backdrop" data-action="close" style="position:absolute;inset:0;background:#10251c3b;z-index:3"></div><dialog class="sheet d${direction}" aria-label="Order receipt export">${header()}<div class="sheet-content">${previewBody()}</div>${footer()}</dialog>`:''}</div>`;}
 const dialog=stage.querySelector('dialog');if(dialog){stage.querySelector('#product-context').inert=true;stage.querySelector('.sidebar')?.setAttribute('inert','');stage.querySelector('.mobile-footer')?.setAttribute('inert','');dialog.show();}
}
function focusStart(){stage.querySelector('[data-action="close"]')?.focus({preventScroll:true});}
function open(){state().step='preview';state().toast='';state().index=0;draw();focusStart();}
function close(){const s=state();if(s.timer)clearTimeout(s.timer);s.busy=false;s.step='orders';draw();stage.querySelector('#open-receipt')?.focus({preventScroll:true});}
async function download(){const s=state(),list=selected().filter(o=>!s.failed.includes(o.id)),opts={customer:s.customer,payment:s.payment,note:s.note};if(!list.length)return;let blob,name;try{if(s.format==='pdf'){blob=SampleReceiptExport.pdf(list,opts);name=list.length===1?`${list[0].ref}-receipt-sample.pdf`:'order-receipts-sample.pdf';}else{const files=await Promise.all(list.map(async o=>({name:o.ref+'-receipt-sample.png',blob:await SampleReceiptExport.png(o,opts)})));blob=files.length===1?files[0].blob:await SampleReceiptExport.zip(files);name=files.length===1?files[0].name:'order-receipts-images-sample.zip';}SampleReceiptExport.download(blob,name);s.toast='Sample '+(s.format==='pdf'?'PDF':list.length>1?'image ZIP':'image')+' downloaded.';draw();stage.querySelector('[data-action="download"]')?.focus({preventScroll:true});}catch{s.toast='Sample export failed. Try again.';draw();}}
function closeShare(){stage.querySelector('.native-share')?.remove();stage.querySelector('.share-backdrop')?.remove();stage.querySelector('[data-share-inert]')?.removeAttribute('inert');stage.querySelector('[data-share-inert]')?.removeAttribute('data-share-inert');stage.querySelector('[data-action=share]')?.focus({preventScroll:true});}
function openShare(){const app=stage.querySelector('.app'),existing=stage.querySelector('dialog')||stage.querySelector('.mobile-preview');existing.setAttribute('data-share-inert','');existing.inert=true;app.insertAdjacentHTML('beforeend',`<div class="share-backdrop" style="position:absolute;inset:0;background:#10251c3b;z-index:8"></div><dialog class="sheet native-share" aria-label="Share receipt"><header class="sheet-header"><div><h2>Share receipt</h2><p class="fine">${scope==='group'?'Order receipts':selected()[0].ref+' receipt'} · ${state().format==='pdf'?'PDF':selected().length>1?'Image ZIP':'PNG image'}</p></div><button class="icon-button" data-action="close-share" aria-label="Close share tray">${icon('close')}</button></header><div class="share-destinations"><button data-destination="WhatsApp"><span class="share-symbol">W</span>WhatsApp</button><button data-destination="Messages"><span class="share-symbol">···</span>Messages</button><button data-destination="Mail"><span class="share-symbol">@</span>Mail</button></div><p class="fine" style="text-align:center">Choose where to share your receipt.</p><button class="quiet" data-action="close-share" style="margin:10px">Cancel</button></dialog>`);app.querySelector('.native-share').show();app.querySelector('.native-share [data-action=close-share]').focus({preventScroll:true});document.getElementById('flow-caption').textContent='Local share-sheet preview · no message is sent';}
stage.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.action==='share')openShare();if(b.dataset.action==='close-share')closeShare();if(b.dataset.destination){closeShare();state().toast='Receipt selected.';stage.querySelector('.toast').textContent=state().toast;document.getElementById('flow-caption').textContent='Local '+b.dataset.destination+' handoff preview · no message is sent';}});
stage.addEventListener('click',event=>{const b=event.target.closest('button,[data-action]');if(!b)return;const s=state();if(b.dataset.single){s.selected=[Number(b.dataset.single)];open();return;}if(b.dataset.retry){s.failed=s.failed.filter(id=>id!==Number(b.dataset.retry));s.toast='Receipt ready. Existing files are kept.';draw();return;}switch(b.dataset.action){case'open':open();break;case'close':close();break;case'deselect':s.selected=[];draw();break;case'previous':s.index=Math.max(0,s.index-1);draw();break;case'next':s.index=Math.min(selected().length-1,s.index+1);draw();break;case'expand':direction=2;state().selected=[...s.selected];state().step='preview';state().format=s.format;state().scenario=s.scenario;state().note=s.note;draw();focusStart();break;case'edit':s.step='preview';s.toast='';draw();focusStart();break;case'prepare':s.busy=true;draw();s.timer=setTimeout(()=>{s.busy=false;s.step='ready';s.failed=s.scenario==='failure'?[selected().at(-1).id]:[];s.toast='';draw();stage.querySelector('[data-action="download"]')?.focus({preventScroll:true});},450);break;case'download':download();break;}});
stage.addEventListener('change',event=>{const el=event.target,s=state();if(el.dataset.pick){const id=Number(el.dataset.pick);s.selected=el.checked?[...new Set([...s.selected,id])]:s.selected.filter(i=>i!==id);draw();stage.querySelector(`[data-pick="${id}"]`)?.focus({preventScroll:true});}else if(el.name==='format'){s.format=el.value;draw();stage.querySelector(`[name=format][value="${s.format}"]`)?.focus({preventScroll:true});}else if(['customer','payment'].includes(el.name)){s[el.name]=el.checked;draw();stage.querySelector(`[name="${el.name}"]`)?.focus({preventScroll:true});}});
stage.addEventListener('input',event=>{if(event.target.name!=='note')return;state().note=event.target.value;stage.querySelectorAll('.receipt-note strong').forEach(n=>n.textContent=event.target.value||'Thank you for shopping with us.');});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state().step!=='orders'){event.preventDefault();if(stage.querySelector('.native-share'))closeShare();else close();}});
document.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>{direction=Number(b.dataset.direction);draw();}));document.querySelectorAll('[data-surface]').forEach(b=>b.addEventListener('click',()=>{surface=b.dataset.surface;draw();}));document.querySelectorAll('[data-scope]').forEach(b=>b.addEventListener('click',()=>{scope=b.dataset.scope;draw();}));
document.getElementById('scenario').addEventListener('change',event=>{const s=state();if(s.timer)clearTimeout(s.timer);s.busy=false;s.scenario=event.target.value;s.failed=[];s.toast='';if(s.step==='ready')s.step='preview';draw();});document.getElementById('theme').addEventListener('change',event=>document.body.dataset.theme=event.target.value);document.getElementById('reset').addEventListener('click',()=>{const s=state();if(s.timer)clearTimeout(s.timer);states.set(key(),initial());draw();});
const hash=location.hash.slice(1).split('/');if([1,2,3].includes(Number(hash[0])))direction=Number(hash[0]);if(['dashboard','mobile'].includes(hash[1]))surface=hash[1];if(['single','group'].includes(hash[2]))scope=hash[2];if(hash[3]==='preview')state().step='preview';draw();
