export const APP_LOCK_QUIET_SEAL_LAYOUT = {
  bodyPaddingTop: 92,
  capCutBottom: -42,
  capCutHeight: 72,
  capHeight: 177,
  choiceLabelFontScaleCap: 1,
  closeButtonSize: 42,
  keyColumnGap: 34,
  keyHeight: 52,
  keyRowGap: 8,
  keypadWidth: 254,
  keyWidth: 62,
  pinCellGap: 10,
  pinCellSize: 28,
  pinRailWidth: 218,
  sealBottom: -37,
  sealSize: 115,
  titleFontSize: 33,
  titleLineHeight: 34,
  topRowPaddingTop: 20,
} as const
