import { describe, expect, test } from "bun:test"

import {
  resolveCustomerConversationQaPath,
  resolveCustomerDeepLink,
  resolveCustomerSystemPath,
} from "./customer-deep-link"

describe("resolveCustomerConversationQaPath", () => {
  test("maps only explicit development QA conversation links", () => {
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversations?qaState=empty",
        true,
      ),
    ).toBe("/(customer)/conversations?qaState=empty")
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversations?qaState=populated",
        true,
      ),
    ).toBe("/(customer)/conversations?qaState=populated")
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversations?qaState=unavailable",
        true,
      ),
    ).toBe("/(customer)/conversations?qaState=unavailable")
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=active",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-active?publicToken=qa-luma&qaState=active",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=new",
        true,
      ),
    ).toBe("/(customer)/conversations/qa-new?publicToken=qa-luma&qaState=new")
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=request-choice",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-request-choice?publicToken=qa-luma&qaState=request-choice",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=attachment-picker",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-attachment-picker?publicToken=qa-luma&qaState=attachment-picker",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=voice-recording",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-voice-recording?publicToken=qa-luma&qaState=voice-recording",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=voice-preview",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-voice-preview?publicToken=qa-luma&qaState=voice-preview",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=foreground-response",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-foreground-response?publicToken=qa-luma&qaState=foreground-response",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=availability-paused",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-availability-paused?publicToken=qa-luma&qaState=availability-paused",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=quote-current",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-quote-current?publicToken=qa-luma&qaState=quote-current",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=account-invitation",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-account-invitation?publicToken=qa-luma&qaState=account-invitation",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=notification-setup",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-notification-setup?publicToken=qa-luma&qaState=notification-setup",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=whatsapp-only",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-whatsapp-only?publicToken=qa-luma&qaState=whatsapp-only",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=whatsapp-bridge",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-whatsapp-bridge?publicToken=qa-luma&qaState=whatsapp-bridge",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=mixed-timeline",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-mixed-timeline?publicToken=qa-luma&qaState=mixed-timeline",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=privacy-restricted",
        true,
      ),
    ).toBe(
      "/(customer)/conversations/qa-privacy-restricted?publicToken=qa-luma&qaState=privacy-restricted",
    )
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversations?qaState=populated",
        false,
      ),
    ).toBeNull()
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversations?qaState=other",
        true,
      ),
    ).toBeNull()
    expect(
      resolveCustomerConversationQaPath(
        "ewatrade-dev://conversation?qaState=new",
        false,
      ),
    ).toBeNull()
  })
})

const PUBLIC_TOKEN = "public-token-123456789012345678901234"
const TRANSFER_TOKEN = "transfer-token-1234567890123456789012"

describe("resolveCustomerSystemPath", () => {
  test("opens an allowlisted Store path without adding credentials", () => {
    expect(
      resolveCustomerSystemPath(`https://chat.ewatrade.com/r/${PUBLIC_TOKEN}`),
    ).toBe(`/r/${PUBLIC_TOKEN}`)
  })

  test("moves an allowlisted fragment transfer into the internal route", () => {
    expect(
      resolveCustomerSystemPath(
        `ewatrade://r/${PUBLIC_TOKEN}#transfer=${TRANSFER_TOKEN}`,
      ),
    ).toBe(`/r/${PUBLIC_TOKEN}`)
    expect(
      resolveCustomerDeepLink(
        `ewatrade://r/${PUBLIC_TOKEN}#transfer=${TRANSFER_TOKEN}`,
      ).pendingTransfer,
    ).toEqual({ publicToken: PUBLIC_TOKEN, transferToken: TRANSFER_TOKEN })
  })

  test("redacts malformed and unrecognized links", () => {
    expect(resolveCustomerSystemPath("ewatrade://orders/private")).toBe("/")
    expect(
      resolveCustomerSystemPath(
        `ewatrade://r/${PUBLIC_TOKEN}#transfer=too-short`,
      ),
    ).toBe(`/r/${PUBLIC_TOKEN}`)
    expect(
      resolveCustomerSystemPath(
        `ewatrade://r/${PUBLIC_TOKEN}#transfer=${TRANSFER_TOKEN}&debug=true`,
      ),
    ).toBe(`/r/${PUBLIC_TOKEN}`)
    expect(resolveCustomerSystemPath("not a valid link")).toBe("/")
  })
})
