const root = document.querySelector('#root');
const dialog = document.querySelector('#dialog');
const state = new Map();
const esc = (v) => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scenarioFields = new Set(['Input layout','Job scenario','Spend authority','Availability preview','Delivery preview','Reuse policy preview','Billing state']);
const icons = ['M3 10 12 3l9 7v11H3Z','M4 4h16v16H4Zm0 5h16M9 9v11','M4 5h16v15H4Zm4-2v5m8-5v5','M3 18h18M6 15V9m6 6V4m6 11v-7'];
const arts = ['ill-grain-feed-sack','ill-cooking-oil','ill-handmade-basket'];
function getState(s,d){const k=`${s.id}/${d}`;if(!state.has(k)) state.set(k,{values:Object.fromEntries(s.fields.map(f=>{const [l,t,v]=f.split('|');return [l,t==='select'?v.split(',')[0]:v]})),selected:0,result:'',done:false});return state.get(k);}
function artwork(i){return `../catalog-illustrations-p1/light/${arts[i%3]}.svg`;}
function field(f,s,d,thumb){const [label,type,raw]=f.split('|');const val=getState(s,d).values[label];const id=`${thumb?'thumb-':''}${s.id}-${d}-${label.replace(/\W/g,'')}`;return `<label for="${id}">${esc(label)}${type==='select'?`<select id="${id}" data-field="${esc(label)}">${raw.split(',').map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input id="${id}" type="${type}" data-field="${esc(label)}" value="${esc(val)}" ${type==='tel'?'inputmode="tel"':''}>`}</label>`;}
function records(s,d){const st=getState(s,d);const query=Object.entries(st.values).find(([k])=>k.startsWith('Search'))?.[1]?.toLowerCase()||'';const cat=st.values.Category||'All';let rows=s.rows.map((r,i)=>({r,i})).filter(({r,i})=>(!query||r.join(' ').toLowerCase().includes(query))&&(cat==='All'||(cat==='Food'?i<2:i===2)));
if(st.values.Sort==='Price low to high') rows.sort((a,b)=>(a.i===1?4200:a.i===0?8500:Infinity)-(b.i===1?4200:b.i===0?8500:Infinity));
if(!rows.length)return '<div class="empty">No matches. Try another search.</div>';
if(s.family==='gallery'&&d===3)return `<div class="visual-grid">${rows.map(({r,i})=>`<article class="visual-card ${st.selected===i?'selected':''}"><img class="art" src="${artwork(i)}" alt=""><strong>${esc(r[0])}</strong><small>${esc(r[1])}</small><button data-pick="${i}" aria-pressed="${st.selected===i}">${st.selected===i?'Selected':'Select'}</button></article>`).join('')}</div>`;
return `<div class="table"><div class="table-head"><span>${s.family==='import'?'Source':'Details'}</span><span>${rows.length} records</span></div>${rows.map(({r,i})=>`<div class="record ${st.selected===i?'selected':''}">${s.family==='gallery'?`<img class="art" src="${artwork(i)}" alt="">`:''}<div><strong>${esc(r[0])}</strong><small>${esc(r[1])}</small></div><button data-pick="${i}" aria-pressed="${st.selected===i}">${st.selected===i?'Selected':'Review'}</button></div>`).join('')}</div>`;
}
function documentPreview(s,d){const st=getState(s,d);const name=st.values['Business name']||'Jawdah Stores';return `<section class="document"><div class="paper ${(st.values.Template||'Minimal').toLowerCase()}"><header><div><h3>${esc(name)}</h3><small>Kano Main</small></div><div class="doc-id">${s.id==='finance-documents'?esc(st.values.Document):'INVOICE'}<br>INV-2026-0041<br>03 October 2026</div></header><small>Bill to</small><p>${esc(st.values.Customer||'Amina Yusuf')}</p>${s.rows.map(r=>`<div class="record"><div><strong>${esc(r[0])}</strong><small>${esc(r[1])}</small></div></div>`).join('')}<footer>Source: ORD-0041 · NGN<br>Thank you for your business.</footer></div></section>`;}
function summary(s){const stats={
 'coin-wallet':[['Available','80 coins'],['Held','20 coins'],['Business','Jawdah']],
 'coin-quote':[['Available','80 coins'],['Quote','20 coins'],['After hold','60 coins']],
 'job-recovery':[['Completed','30'],['Needs review','5'],['Retained','9']],
 'billing-plans':[['Active Items','120'],['Staff','2'],['Stores','1']],
 'document-batch':[['Selected','4'],['Eligible','3'],['Excluded','1']]
};const a=stats[s.id];return a?`<div class="summary">${a.map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div>`:'';}
function product(s,d){const st=getState(s,d);const unavailable=st.values['Availability preview']==='Unavailable';return `<div class="product-hero"><img src="${artwork(0)}" alt="Rice bag illustration"><div><small>JAWDAH STORES</small><h3>Rice bag ${esc(st.values.Option||'5 kg')}</h3><p>${st.values.Option==='10 kg'?'₦16,500':'₦8,500'}</p><span class="badge">${unavailable?'Unavailable':'Confirm availability'}</span></div></div>`;}
function app(s,d,thumb=false){const st=getState(s,d);const mobile=document.querySelector('#surface').value==='mobile';const dark=document.querySelector('#theme').value==='dark';const gallery=s.family==='gallery';const customer=['public-product','public-browse'].includes(s.id);const visual=s.family==='document'?documentPreview(s,d):s.id==='public-product'?product(s,d):records(s,d);
return `<section class="app d${d} family-${s.family} ${customer?'customer':''} ${dark?'dark':''} ${mobile?'mobile-shell':''}" data-study="${s.id}" data-direction="${d}"><aside class="rail" aria-hidden="true"><img src="../../apps/dashboard/public/brand/ewatrade-mark-precision-rise-v1${dark?'-reverse':''}.svg" alt="">${icons.map((p,i)=>`<svg class="${i===1?'active':''}" viewBox="0 0 24 24"><path d="${p}"/></svg>`).join('')}<div class="avatar">JS</div></aside><div class="app-main"><header class="appbar"><strong>Jawdah Stores</strong><span>Kano Main</span></header><div class="page"><header class="page-head"><div><div class="kicker">${esc(s.group)}</div><h2>${esc(s.id==='public-product'?'Rice bag':s.id==='public-browse'?'Products':s.title)}</h2></div></header>${d!==2?summary(s):''}<div class="layout">${d===2?'<aside class="steps"><div>01 · Choose</div><div>02 · Review</div><div>03 · Finish</div></aside>':''}<div class="records">${visual}</div><form class="editor"><h3>${d===1?'Review details':d===2?'Your choices':'Options'}</h3>${s.fields.filter(f=>!scenarioFields.has(f.split('|')[0])).map(f=>field(f,s,d,thumb)).join('')}<button type="submit" class="primary" data-action ${s.id==='public-product'&&st.values['Availability preview']==='Unavailable'?'disabled':''}>${esc(s.action.replace('sample ','').replace('proposed ','').replace('sample',''))}</button></form></div><div class="status" role="status">${esc(st.result)}</div>${st.done?resultActions(s):''}</div>${mobile&&!s.id.startsWith('public-')?'<footer class="bottom-dock" aria-label="Existing app navigation"><span>Home</span><span>Orders</span><span>＋</span><span>Catalog</span><span>More</span></footer>':''}</div></section>`;
}
function resultActions(s){if(s.id==='ai-product'||s.id==='ai-logo')return '<div class="action-row"><button data-follow="Use image">Use image</button><button data-follow="Keep in gallery">Keep in gallery</button><button data-follow="New quote">New variation</button></div>';if(s.id==='document-batch')return '<div class="action-row"><button data-follow="Retry failed">Retry failed</button><button data-follow="Download manifest">Download manifest</button></div>';if(s.id==='public-publish'||s.id==='public-contact'||s.id==='public-product')return '<div class="action-row"><button data-follow="Copy draft">Copy draft</button></div>';if(s.family==='document'||s.id==='import-samples')return '<div class="action-row"><button data-follow="Download preview">Download sample record</button></div>';return '';}
function rationale(s){return s.recommended===1?'Matches the approved Stock ledger: comparable rows and a persistent detail panel.':s.recommended===2?'Follows Catalog Direction 02: focused editing, retained choices and a clear return.':'Gives imagery priority while retaining the current typography, spacing and restrained controls.';}
function nav(active){const groups=[...new Set(studies.map(s=>s.group))];return `<nav class="study-nav" aria-label="Feature studies">${groups.map(g=>`<h3>${g}</h3>${studies.filter(s=>s.group===g).map(s=>`<a class="${s.id===active?'active':''}" href="#${s.id}"><span>P${String(s.phase).padStart(2,'0')}</span>${s.title}</a>`).join('')}`).join('')}</nav>`;}
function render(){const [id,dRaw]=location.hash.slice(1).split('/');const s=studies.find(x=>x.id===id)||studies[0];const d=Number(dRaw);if(d>=1&&d<=3){root.innerHTML=`<header class="reviewbar"><a href="#${s.id}">← Three directions</a><strong>${s.title} · 0${d}</strong><nav aria-label="Directions">${[1,2,3].map(i=>`<a href="#${s.id}/${i}" class="${i===d?'active':''}">0${i}${i===s.recommended?' ★':''}</a>`).join('')}</nav><small>Interactive sample · No live writes or payments · ${directionNames[d-1]}</small></header><p class="surface-note">${esc(s.rule)}${document.querySelector('#surface').value==='mobile'&&s.group==='Imports'?' Import UI remains dashboard-first; this is a narrow-browser check.':''}</p><div class="fixture-controls">${s.fields.filter(f=>scenarioFields.has(f.split('|')[0])).map(f=>field(f,s,d,false)).join('')}</div><div class="stage">${app(s,d)}</div><footer class="footer">${s.tasks} · ${rationale(s)} <button data-reset-one>Reset this direction</button></footer>`;wire(s,d);return;}
root.innerHTML=`<section class="intro"><div><div class="kicker">18 phases / ${studies.length} feature studies / ${studies.length*3} directions</div><h1>Plan the next screens.</h1><p>Three directions per feature. Recommended choices preserve the current dashboard and Catalog patterns.</p></div></section><div class="workspace">${nav(s.id)}<section class="comparison"><header class="study-heading"><div><div class="kicker">Phase ${s.phase} · ${s.group}</div><h2>${s.title}</h2><p>${s.description}</p></div></header><div class="directions">${[1,2,3].map(d=>`<article class="direction"><header><h3>0${d} · ${directionNames[d-1]}</h3>${s.recommended===d?'<span class="badge recommend">Recommended</span>':''}</header><div class="thumbnail" inert>${app(s,d,true)}</div><p>${directionTradeoffs[d-1]}</p><a class="open" href="#${s.id}/${d}">Try direction 0${d} <span>↗</span></a></article>`).join('')}</div><div class="notes"><section><strong>Why 0${s.recommended}</strong><p>${rationale(s)}</p><p>${s.rule}</p></section><section><strong>Plan coverage</strong><p><code>${s.tasks}</code></p><p>Local samples only. Recommendations do not adopt pending commercial policies.</p></section></div></section></div>`;
}
function outcome(s,st){const v=st.values;if(s.id==='media-library'&&st.selected===2)return 'Image is still under review. Choose an approved image.';if(s.id==='media-library')return `${s.rows[st.selected][0]} attached to this draft. Original retained.`;
if(s.id==='media-usage'){if(v.Operation==='Delete from gallery')return 'Cannot delete: another Product uses this image.';if(v.Operation==='Replace this attachment')return 'Attachment replaced on this Product. Original remains in My images.';}
if(s.id==='import-entry'){if(v['Input layout']==='Unknown layout')return 'Layout not recognized. Choose manual mapping or request AI mapping explicitly.';if(v['Input layout']==='Invalid template')return 'Required fields missing. Correct the template before continuing.';}
if(s.id==='public-settings')return v['Complete pause']==='On'?'Public access paused. Product pages and browsing are unavailable.':v.Browsing==='On'?'Browsing enabled. Published Products appear in the public store.':'Browsing off. Published Product links remain public.';
if(s.id==='public-contact'&&!/^\+[1-9]\d{7,14}$/.test(v.Contact))return 'Enter a valid international phone number.';
if(s.id==='public-contact')return v['Delivery preview']==='No WhatsApp installed'?'WhatsApp unavailable. Copy the prepared message.':`Prepared for ${v.Contact}. No message sent.`;
if(s.id==='public-product')return `Draft: Hello, is Rice bag ${v.Option} available? ewatrade.com/jawdah/rice-bag`;
if(s.id==='public-browse')return `${s.rows[st.selected][0]} opened. Your search and filters are retained.`;
if(s.id==='billing-plans'){const prices={Starter:[3000,9000,30000],Growth:[8000,24000,80000],Pro:[20000,60000,200000]};const idx=['Monthly','Quarterly','Annual'].indexOf(v.Period);return `${v.Plan} · ₦${prices[v.Plan][idx].toLocaleString()} payable ${v.Period.toLowerCase()}. Proposal only.`;}
if(s.id==='coin-quote'){if(v['Spend authority']==='Staff cap exceeded')return 'Spend limit reached. No coins held.';if(v['Job scenario']==='Rejected')return 'Result rejected. 20-coin hold released. Available: 80.';if(v['Job scenario']==='Provider uncertain')return 'Result uncertain. 20 coins remain held. Reconcile before retrying.';}
if(s.id==='public-image-consent')return v.Rights==='Not confirmed'?'Confirm reuse rights before proceeding.':'Rights confirmation retained. Publication awaits the adopted reuse policy.';
if(s.id==='document-branding')return `${v.Template} saved for future documents. Issued documents unchanged.`;
return s.outcome;}
function wire(s,d){const st=getState(s,d);document.querySelectorAll('[data-field]').forEach(el=>{const handler=()=>{st.values[el.dataset.field]=el.value;if(s.id==='billing-plans'&&el.dataset.field==='Plan')st.selected=['Starter','Growth','Pro'].indexOf(el.value);if(el.tagName==='SELECT')render();else if(el.dataset.field.startsWith('Search')){const wrap=document.querySelector('.records');wrap.innerHTML=records(s,d);wirePicks(s,d);}};el.addEventListener(el.tagName==='SELECT'?'change':'input',handler);});wirePicks(s,d);
document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const opener=document.querySelector('[data-action]');dialog.className=document.querySelector('#theme').value==='dark'?'dark-dialog':'';dialog.innerHTML=`<h2 id="dialog-title">Review ${esc(s.title.toLowerCase())}</h2><p>Jawdah Stores · Kano Main</p><dl>${Object.entries(st.values).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd>`).join('')}</dl><p>${esc(s.rows[st.selected][0])}</p><p class="muted">Workshop sample. No live changes.</p><footer><button id="cancel">Back</button><button class="primary" id="confirm">Confirm preview</button></footer>`;dialog.showModal();document.querySelector('#cancel').onclick=()=>dialog.close();document.querySelector('#confirm').onclick=()=>{st.result=outcome(s,st);st.done=true;dialog.close();render();document.querySelector('.status').scrollIntoView({block:'nearest'});document.querySelector('[data-action]').focus({preventScroll:true});};dialog.onclose=()=>opener?.focus({preventScroll:true});});
document.querySelector('[data-reset-one]').onclick=()=>{state.delete(`${s.id}/${d}`);render();};document.querySelectorAll('[data-follow]').forEach(el=>el.onclick=()=>{const a=el.dataset.follow;if(a.startsWith('Download')){const blob=new Blob([JSON.stringify({sample:true,feature:s.id,values:st.values,result:st.result},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${s.id}-sample.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);st.result='Sample record downloaded. PDF and image rendering require the production document engine.';}else if(a==='Use image')st.result='Image applied to the selected draft. Original retained.';else if(a==='Keep in gallery')st.result='Saved in My images. Current attachment unchanged.';else if(a==='New quote')st.result='New variation requires a fresh quote. No coins spent.';else if(a==='Retry failed')st.result='Failed item recovered. 3 files ready; canceled Order excluded. Existing invoice identities retained.';else if(a==='Copy draft'){dialog.innerHTML=`<h2 id="dialog-title">Copy draft</h2><textarea aria-label="Prepared message" readonly style="width:100%;min-height:120px;padding:12px">${esc(st.result)}</textarea><footer><button id="close-copy">Done</button></footer>`;dialog.showModal();dialog.querySelector('textarea').select();dialog.querySelector('#close-copy').onclick=()=>dialog.close();return;}render();});}
function wirePicks(s,d){document.querySelectorAll('[data-pick]').forEach(el=>el.onclick=()=>{const st=getState(s,d);st.selected=Number(el.dataset.pick);if(s.id==='billing-plans')st.values.Plan=['Starter','Growth','Pro'][st.selected];render();});}
document.querySelector('#theme').onchange=render;document.querySelector('#surface').onchange=render;document.querySelector('#reset').onclick=()=>{state.clear();if(dialog.open)dialog.close();document.querySelector('#theme').value='light';document.querySelector('#surface').value='desktop';render();};window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();
