import { generalActionSchema } from "../general/contracts"
import type { Capability, CapabilityRole, WriteCapability } from "./types"

const everyone: CapabilityRole[] = [
  "OWNER",
  "ADMIN",
  "MANAGER",
  "CASHIER",
  "OPERATOR",
]
const managers: CapabilityRole[] = ["OWNER", "ADMIN", "MANAGER"]
const brain = ".brain/features/assistant-business-operations.md"
const actionSchema = (action: string) => {
  const schema = generalActionSchema.options.find(
    (option) => option.shape.action.value === action,
  )
  if (!schema) throw Error(`No proposal schema for ${action}`)
  return schema
}
const proposalTests = [
  "apps/api/src/assistant/general-proposals.integration.test.ts",
  "packages/assistant/src/general/contracts.test.ts",
]

/**
 * Every assistant capability, in model-listing order. Changing behaviour means
 * bumping `version`; IDs are permanent. Server executors live in the API.
 */
export const capabilityManifest = [
  {
    id: "search.records",
    version: 1,
    mode: "read",
    title: "Search saved records",
    domain: "search",
    tool: "searchRecords",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["search.global"],
    examples: ["Find Amina", "Do we have eggs?"],
    tests: ["apps/api/src/assistant/general-availability.test.ts"],
    brain,
  },
  {
    id: "catalog.item.read",
    version: 1,
    mode: "read",
    title: "Read a product and its prices",
    domain: "catalog",
    tool: "readCatalogItem",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["catalog.getItem"],
    examples: ["How much is a crate of eggs?"],
    tests: [],
    brain,
  },
  {
    id: "inventory.offering_stock.read",
    version: 1,
    mode: "read",
    title: "Read stock for an offering",
    domain: "inventory",
    tool: "readOfferingStock",
    policy: { roles: managers },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["inventory.configuredOfferingAvailability"],
    examples: ["How many crates of eggs are left?"],
    tests: [],
    brain,
  },
  {
    id: "sales.orders.read",
    version: 1,
    mode: "read",
    title: "Read a page of orders",
    domain: "sales",
    tool: "readOrders",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["orders.listPage"],
    examples: ["Show today's orders"],
    tests: [],
    brain,
  },
  {
    id: "sales.summary.read",
    version: 1,
    mode: "read",
    title: "Read sales totals for a period",
    domain: "sales",
    tool: "readSalesSummary",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["orders.reportSummary"],
    examples: ["How much did we sell this week?"],
    tests: [],
    brain,
  },
  {
    id: "sales.order.read",
    version: 1,
    mode: "read",
    title: "Read one order",
    domain: "sales",
    tool: "readOrder",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["orders.get"],
    examples: ["Has order 1042 been paid?"],
    tests: [],
    brain,
  },
  {
    id: "services.queue.read",
    version: 1,
    mode: "read",
    title: "Read the service work queue",
    domain: "services",
    tool: "readServices",
    policy: { roles: managers },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["services.queuePage"],
    examples: ["Which jobs are overdue?"],
    tests: [],
    brain,
  },
  {
    id: "customers.accounts.read",
    version: 1,
    mode: "read",
    title: "Read customer ledger accounts",
    domain: "customers",
    tool: "readCustomerAccounts",
    policy: { roles: ["OWNER", "ADMIN"] },
    scope: "tenant",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["customerLedger.accounts"],
    examples: ["How much does Amina owe?"],
    tests: [],
    brain,
  },
  {
    id: "customers.create",
    version: 1,
    mode: "write",
    action: "customer_create",
    schema: actionSchema("customer_create"),
    effect: "record",
    receipt: "customer",
    title: "Add a customer",
    domain: "customers",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["customers.create"],
    examples: ["Add Amina, 0803 000 0000"],
    tests: proposalTests,
    brain,
  },
  {
    id: "catalog.product.create",
    version: 1,
    mode: "write",
    action: "product_create",
    schema: actionSchema("product_create"),
    effect: "record",
    receipt: "product",
    title: "Add a simple product",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["catalog.createSimpleItem"],
    examples: ["Add Eggs at ₦200 per piece"],
    tests: proposalTests,
    brain,
  },
  {
    id: "sales.order.create",
    version: 1,
    mode: "write",
    action: "order_create",
    schema: actionSchema("order_create"),
    effect: "record",
    receipt: "order",
    title: "Create a sale",
    domain: "sales",
    tool: "draftAction",
    policy: { roles: everyone },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["orders.create"],
    examples: ["Sell two crates of eggs to Amina"],
    tests: proposalTests,
    brain,
  },
  {
    id: "sales.payment.record",
    version: 1,
    mode: "write",
    action: "payment_record",
    schema: actionSchema("payment_record"),
    effect: "record",
    receipt: "payment",
    title: "Record money received for an order",
    domain: "sales",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["mobile"],
    rollout: "source",
    procedures: ["orders.recordPayment"],
    examples: ["Amina paid ₦300 cash for order 1042"],
    tests: proposalTests,
    brain,
  },
] as const satisfies readonly Capability[]

export type CapabilityId = (typeof capabilityManifest)[number]["id"]
export const writeCapabilities = capabilityManifest.filter(
  (capability): capability is Extract<typeof capability, WriteCapability> =>
    capability.mode === "write",
)
export function capabilityForAction(action: string) {
  const capability = writeCapabilities.find((entry) => entry.action === action)
  if (!capability) throw Error(`No capability for action ${action}`)
  return capability
}
