import { generalActionSchema } from "../general/contracts"
import type { Capability, CapabilityRole, WriteCapability } from "./types"

const everyone: CapabilityRole[] = [
  "OWNER",
  "ADMIN",
  "MANAGER",
  "CASHIER",
  "OPERATOR",
]
const managers: CapabilityRole[] = ["OWNER", "ADMIN", "MANAGER"]
const brain = ".brain/features/assistant-business-operations.md"
const actionSchema = (action: string) => {
  const schema = generalActionSchema.options.find(
    (option) => option.shape.action.value === action,
  )
  if (!schema) throw Error(`No proposal schema for ${action}`)
  return schema
}
const proposalTests = [
  "apps/api/src/assistant/general-proposals.integration.test.ts",
  "packages/assistant/src/general/contracts.test.ts",
]

/**
 * Every assistant capability, in model-listing order. Changing behaviour means
 * bumping `version`; IDs are permanent. Server executors live in the API.
 */
export const capabilityManifest = [
  {
    id: "search.records",
    version: 1,
    mode: "read",
    title: "Search saved records",
    domain: "search",
    tool: "searchRecords",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["search.global"],
    examples: ["Find Amina", "Do we have eggs?"],
    tests: ["apps/api/src/assistant/general-availability.test.ts"],
    brain,
  },
  {
    id: "catalog.history.read",
    version: 1,
    mode: "read",
    title: "Read item order and activity history",
    domain: "catalog",
    tool: "readCatalogHistory",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.detail.orders", "catalog.detail.activity"],
    examples: ["Show this item's history"],
    tests: [
      "apps/api/src/assistant/general-catalog-history.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.item.read",
    version: 1,
    mode: "read",
    title: "Read a product and its prices",
    domain: "catalog",
    tool: "readCatalogItem",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["catalog.detail.overview"],
    examples: ["How much is a crate of eggs?"],
    tests: [],
    brain,
  },
  {
    id: "inventory.totals.read",
    version: 1,
    mode: "read",
    title: "Read compatible inventory totals",
    domain: "inventory",
    tool: "readInventoryTotals",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.compatibleTotalsPage"],
    examples: ["Show compatible stock totals"],
    tests: [
      "packages/db/src/queries/inventory-reporting.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "inventory.balances.read",
    version: 1,
    mode: "read",
    title: "Read inventory balance sources",
    domain: "inventory",
    tool: "readInventoryBalances",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.balancePage"],
    examples: ["Show stock balance sources"],
    tests: [
      "apps/api/src/assistant/general-inventory-balances.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "inventory.offering_stock.read",
    version: 1,
    mode: "read",
    title: "Read stock for an offering",
    domain: "inventory",
    tool: "readOfferingStock",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["inventory.configuredOfferingAvailability"],
    examples: ["How many crates of eggs are left?"],
    tests: [],
    brain,
  },
  {
    id: "sales.orders.read",
    version: 1,
    mode: "read",
    title: "Read a page of orders",
    domain: "sales",
    tool: "readOrders",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["orders.listPage"],
    examples: ["Show today's orders"],
    tests: [],
    brain,
  },
  {
    id: "sales.summary.read",
    version: 1,
    mode: "read",
    title: "Read sales totals for a period",
    domain: "sales",
    tool: "readSalesSummary",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["orders.reportSummary"],
    examples: ["How much did we sell this week?"],
    tests: [],
    brain,
  },
  {
    id: "sales.order.read",
    version: 1,
    mode: "read",
    title: "Read one order",
    domain: "sales",
    tool: "readOrder",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["orders.get"],
    examples: ["Has order 1042 been paid?"],
    tests: [],
    brain,
  },
  {
    id: "services.queue.read",
    version: 1,
    mode: "read",
    title: "Read the service work queue",
    domain: "services",
    tool: "readServices",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["services.queuePage"],
    examples: ["Which jobs are overdue?"],
    tests: [],
    brain,
  },
  {
    id: "customers.receivables.read",
    version: 1,
    mode: "read",
    title: "Read customer ledger receivables",
    domain: "customers",
    tool: "readReceivables",
    policy: { roles: ["OWNER", "ADMIN"] },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["customerLedger.receivables"],
    examples: ["Show customer ledger debt and credit"],
    tests: [
      "apps/api/src/assistant/general-receivables.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "customers.accounts.read",
    version: 1,
    mode: "read",
    title: "Read customer ledger accounts",
    domain: "customers",
    tool: "readCustomerAccounts",
    policy: { roles: ["OWNER", "ADMIN"] },
    scope: "tenant",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["customerLedger.accounts"],
    examples: ["How much does Amina owe?"],
    tests: [],
    brain,
  },
  {
    id: "customers.read",
    version: 1,
    mode: "read",
    title: "Read one customer and their recent orders",
    domain: "customers",
    tool: "readCustomer",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["customers.getById"],
    examples: ["What is Amina's phone number?"],
    tests: ["apps/api/src/assistant/general-access.test.ts"],
    brain,
  },
  {
    id: "customers.create",
    version: 1,
    mode: "write",
    action: "customer_create",
    schema: actionSchema("customer_create"),
    effect: "record",
    receipt: "customer",
    title: "Add a customer",
    domain: "customers",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["customers.create"],
    examples: ["Add Amina, 0803 000 0000"],
    tests: proposalTests,
    brain,
  },
  {
    id: "catalog.product.create",
    version: 1,
    mode: "write",
    action: "product_create",
    schema: actionSchema("product_create"),
    effect: "record",
    receipt: "product",
    title: "Add a simple product",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["catalog.createSimpleItem"],
    examples: ["Add Eggs at ₦200 per piece"],
    tests: proposalTests,
    brain,
  },
  {
    id: "sales.order.create",
    version: 1,
    mode: "write",
    action: "order_create",
    schema: actionSchema("order_create"),
    effect: "record",
    receipt: "order",
    title: "Create a sale",
    domain: "sales",
    tool: "draftAction",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["orders.create"],
    examples: ["Sell two crates of eggs to Amina"],
    tests: proposalTests,
    brain,
  },
  {
    id: "sales.payment.record",
    version: 1,
    mode: "write",
    action: "payment_record",
    schema: actionSchema("payment_record"),
    effect: "record",
    receipt: "payment",
    title: "Record money received for an order",
    domain: "sales",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["orders.recordPayment"],
    examples: ["Amina paid ₦300 cash for order 1042"],
    tests: proposalTests,
    brain,
  },
  {
    id: "customers.update",
    version: 1,
    mode: "write",
    action: "customer_update",
    schema: actionSchema("customer_update"),
    effect: "record",
    receipt: "customer",
    title: "Update a customer's details",
    domain: "customers",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard", "mobile"],
    rollout: "source",
    procedures: ["customers.update"],
    examples: ["Change Amina's phone to 0803 111 2222"],
    tests: proposalTests,
    brain,
  },
  {
    id: "catalog.price.update",
    version: 1,
    mode: "write",
    action: "product_price_update",
    schema: actionSchema("product_price_update"),
    effect: "record",
    receipt: "product",
    title: "Update a product price",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.updatePrice"],
    examples: ["Change the Big Eggs Piece price to ₦250"],
    tests: [
      "packages/db/src/queries/catalog-price-update.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.details.update",
    version: 1,
    mode: "write",
    action: "product_details_update",
    schema: actionSchema("product_details_update"),
    effect: "record",
    receipt: "product",
    title: "Update product details",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.updateProductDetails"],
    examples: [],
    tests: [
      "packages/db/src/queries/catalog-product-update.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.identifiers.update",
    version: 1,
    mode: "write",
    action: "product_identifiers_update",
    schema: actionSchema("product_identifiers_update"),
    effect: "record",
    receipt: "product",
    title: "Update selling-unit identifiers",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.updateProductIdentifiers"],
    examples: [],
    tests: [
      "packages/db/src/queries/catalog-product-update.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.availability.update",
    version: 1,
    mode: "write",
    action: "product_availability_update",
    schema: actionSchema("product_availability_update"),
    effect: "record",
    receipt: "product",
    title: "Change selling availability",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.setOfferingAvailability"],
    examples: [],
    tests: [
      "packages/db/src/queries/catalog-availability.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.units.draft",
    version: 1,
    mode: "write",
    action: "product_unit_configuration_draft",
    schema: actionSchema("product_unit_configuration_draft"),
    effect: "record",
    receipt: "product",
    title: "Save a unit configuration draft",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: [
      "catalog.createUnitConfigurationDraft",
      "catalog.updateUnitConfigurationDraft",
    ],
    examples: [],
    tests: [
      "packages/db/src/queries/catalog-unit-configuration-safety.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.units.publish",
    version: 1,
    mode: "write",
    action: "product_unit_configuration_publish",
    schema: actionSchema("product_unit_configuration_publish"),
    effect: "record",
    receipt: "product",
    title: "Publish a unit configuration",
    domain: "catalog",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.publishUnitConfiguration"],
    examples: [],
    tests: [
      "packages/db/src/queries/catalog-unit-configuration-safety.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "sales.orders.summary",
    version: 1,
    mode: "read",
    title: "Read exact order counts and unpaid amounts",
    domain: "sales",
    tool: "readOrderSummary",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["orders.operationalSummary"],
    examples: ["How much does this customer owe on orders?"],
    tests: [
      "packages/db/src/queries/commercial-order-operational-summary.test.ts",
      "apps/api/src/assistant/general-operational-summary-contract.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "inventory.low_stock.read",
    version: 1,
    mode: "read",
    title: "Read a page of low stock",
    domain: "inventory",
    tool: "readLowStock",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.lowStockPage"],
    examples: ["Which offerings have at most two available units?"],
    tests: [
      "packages/db/src/queries/catalog-low-stock.test.ts",
      "apps/api/src/assistant/general-low-stock.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.count",
    version: 1,
    mode: "read",
    title: "Count catalog items",
    domain: "catalog",
    tool: "readCatalogCount",
    policy: { roles: everyone },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.count"],
    examples: ["Count catalog items"],
    tests: ["apps/api/src/assistant/general-counts.test.ts", ...proposalTests],
    brain,
  },
  {
    id: "sales.order_contacts.count",
    version: 1,
    mode: "read",
    title: "Count order contact identities",
    domain: "sales",
    tool: "readOrderContactCount",
    policy: { roles: everyone },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["orders.customerCount"],
    examples: ["Count order contact identities"],
    tests: [
      "apps/api/src/assistant/general-order-contact-count.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "customers.count",
    version: 1,
    mode: "read",
    title: "Count saved customers",
    domain: "customers",
    tool: "readCustomerCount",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["customers.count"],
    examples: ["Count saved customers"],
    tests: ["apps/api/src/assistant/general-counts.test.ts", ...proposalTests],
    brain,
  },
  {
    id: "stores.count",
    version: 1,
    mode: "read",
    title: "Count accessible Stores",
    domain: "search",
    tool: "readStoreCount",
    policy: { roles: everyone },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["tenant.stores"],
    examples: ["Count accessible Stores"],
    tests: ["apps/api/src/assistant/general-counts.test.ts", ...proposalTests],
    brain,
  },
  {
    id: "customers.page",
    version: 1,
    mode: "read",
    title: "Read a customer directory page",
    domain: "customers",
    tool: "readCustomers",
    policy: { roles: managers },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["customers.listPage"],
    examples: ["Find customers named Amina and show the next page"],
    tests: [
      "apps/api/src/assistant/general-lookup-inputs.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "catalog.page",
    version: 1,
    mode: "read",
    title: "Read a catalog page",
    domain: "catalog",
    tool: "readCatalogPage",
    policy: { roles: everyone },
    scope: "tenant",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["catalog.listItemsPage"],
    examples: ["Find eggs and show the next page"],
    tests: [
      "apps/api/src/assistant/general-lookup-inputs.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "sales.orders.lookup",
    version: 1,
    mode: "read",
    title: "Look up open orders",
    domain: "sales",
    tool: "lookupOpenOrders",
    policy: { roles: everyone },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["orders.lookupOpenPage"],
    examples: ["Find this customer's open orders"],
    tests: [
      "apps/api/src/assistant/general-open-order.test.ts",
      ...proposalTests,
    ],
    brain,
  },
  {
    id: "inventory.stock.receive",
    version: 1,
    mode: "write",
    action: "stock_receive",
    schema: actionSchema("stock_receive"),
    effect: "record",
    receipt: "inventory",
    title: "Receive stock",
    domain: "inventory",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: [
      "inventory.postBalanceOperation",
      "inventory.categorySuggestions",
    ],
    examples: ["Receive three crates into this Store"],
    tests: [
      "apps/api/src/assistant/general-stock-receipt.integration-check.ts",
    ],
    brain,
  },
  {
    id: "inventory.stock.adjust",
    version: 1,
    mode: "write",
    action: "stock_adjust",
    schema: actionSchema("stock_adjust"),
    effect: "record",
    receipt: "inventory",
    title: "Adjust stock or record waste",
    domain: "inventory",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: [
      "inventory.postBalanceOperation",
    ],
    examples: ["Adjust stock or record waste"],
    tests: [
      "packages/assistant/src/general/stock-adjustment.test.ts",
    ],
    brain,
  },
  {
    id: "inventory.stock.correct",
    version: 1,
    mode: "write",
    action: "stock_correct",
    schema: actionSchema("stock_correct"),
    effect: "record",
    receipt: "inventory",
    title: "Correct an original stock operation",
    domain: "inventory",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: [
      "inventory.correctOperation",
    ],
    examples: ["Correct an original stock operation"],
    tests: [
      "packages/assistant/src/general/stock-adjustment.test.ts",
    ],
    brain,
  },
  {
    id: "inventory.count.create",
    version: 1,
    mode: "write",
    action: "stock_count_create",
    schema: actionSchema("stock_count_create"),
    effect: "record",
    receipt: "stock_count",
    title: "Create stock count",
    domain: "inventory",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.createStockCount"],
    examples: ["Create stock count after reviewing observations"],
    tests: ["apps/api/src/assistant/general-stock-count.integration-check.ts"],
    brain,
  },

  {
    id: "inventory.count.finalize",
    version: 1,
    mode: "write",
    action: "stock_count_finalize",
    schema: actionSchema("stock_count_finalize"),
    effect: "record",
    receipt: "stock_count",
    title: "Finalize stock count",
    domain: "inventory",
    tool: "draftAction",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.finalizeStockCount"],
    examples: ["Finalize stock count after reviewing observations"],
    tests: ["apps/api/src/assistant/general-stock-count.integration-check.ts"],
    brain,
  },
  {
    id: "inventory.count.read",
    version: 1,
    mode: "read",
    title: "Read stock count",
    domain: "inventory",
    tool: "readStockCount",
    policy: { roles: managers },
    scope: "store",
    clients: ["dashboard"],
    rollout: "source",
    procedures: ["inventory.stockCountReview"],
    examples: ["Review my saved physical count"],
    tests: ["apps/api/src/assistant/general-stock-count.integration-check.ts"],
    brain,
  },
  {
    id: "inventory.operations.history", version: 1, mode: "read", title: "Read recent stock operations",
    domain: "inventory", tool: "readStockOperations", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.operationHistory"],
    examples: ["Read recent stock operations"], tests: ["packages/db/src/queries/inventory-correction-target.test.ts"], brain,
  },
  {
    id: "inventory.operations.read", version: 1, mode: "read", title: "Read original stock operation",
    domain: "inventory", tool: "readStockOperation", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.operationAudit"],
    examples: ["Read original stock operation"], tests: ["packages/db/src/queries/inventory-correction-target.test.ts"], brain,
  },
  {
    id: "inventory.closeout.create", version: 1, mode: "write", action: "inventory_closeout_create",
    schema: actionSchema("inventory_closeout_create"), effect: "record", receipt: "inventory_closeout",
    title: "Save custody closeout declarations", domain: "inventory", tool: "draftAction", policy: { roles: managers },
    scope: "store", clients: ["dashboard"], rollout: "source", procedures: ["inventory.createCloseout"],
    examples: ["Save the declared stock at shift end"], tests: ["packages/assistant/src/general/closeout.test.ts"], brain,
  },
  {
    id: "inventory.closeout.finalize", version: 1, mode: "write", action: "inventory_closeout_finalize",
    schema: actionSchema("inventory_closeout_finalize"), effect: "record", receipt: "inventory_closeout",
    title: "Finalize reviewed custody closeout", domain: "inventory", tool: "draftAction", policy: { roles: managers },
    scope: "store", clients: ["dashboard"], rollout: "source", procedures: ["inventory.finalizeCloseout"],
    examples: ["Finalize the saved custody declarations"], tests: ["packages/assistant/src/general/closeout.test.ts"], brain,
  },
  {
    id: "inventory.closeout.list", version: 1, mode: "read", title: "Find recent custody closeouts",
    domain: "inventory", tool: "readInventoryCloseouts", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.closeouts"],
    examples: ["Find draft custody closeouts"], tests: ["packages/db/src/queries/inventory-closeout-review.test.ts"], brain,
  },
  {
    id: "inventory.closeout.read", version: 1, mode: "read", title: "Review a saved custody closeout",
    domain: "inventory", tool: "readInventoryCloseout", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.closeoutReview"],
    examples: ["Show declared stock and reconciliation conflicts"], tests: ["packages/db/src/queries/inventory-closeout-review.test.ts"], brain,
  },
  {
    id: "inventory.transfer.list", version: 1, mode: "read", title: "Find Store transfers",
    domain: "inventory", tool: "readStockTransfers", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.transfers"],
    examples: ["Find stock still in transit"], tests: ["packages/db/src/queries/inventory-transfer-review.test.ts"], brain,
  },
  {
    id: "inventory.transfer.read", version: 1, mode: "read", title: "Read a saved Store transfer",
    domain: "inventory", tool: "readStockTransfer", policy: { roles: managers }, scope: "store",
    clients: ["dashboard"], rollout: "source", procedures: ["inventory.transferReview"],
    examples: ["Show receipt history and remaining transit stock"], tests: ["packages/db/src/queries/inventory-transfer-review.test.ts"], brain,
  },
  {
    id: "inventory.transfer.dispatch", version: 1, mode: "write", action: "stock_transfer_dispatch",
    schema: actionSchema("stock_transfer_dispatch"), effect: "record", receipt: "stock_transfer",
    title: "Dispatch stock to another Store", domain: "inventory", tool: "draftAction", policy: { roles: managers },
    scope: "store", clients: ["dashboard"], rollout: "source", procedures: ["inventory.dispatchTransfer"],
    examples: ["Dispatch stock to another Store"], tests: ["packages/assistant/src/general/stock-transfer.test.ts"], brain,
  },
  {
    id: "inventory.transfer.receive", version: 1, mode: "write", action: "stock_transfer_receive",
    schema: actionSchema("stock_transfer_receive"), effect: "record", receipt: "stock_transfer",
    title: "Acknowledge stock received at this Store", domain: "inventory", tool: "draftAction", policy: { roles: managers },
    scope: "store", clients: ["dashboard"], rollout: "source", procedures: ["inventory.transitionTransfer"],
    examples: ["Acknowledge stock received at this Store"], tests: ["packages/assistant/src/general/stock-transfer.test.ts"], brain,
  },
  {
    id: "inventory.transfer.cancel", version: 1, mode: "write", action: "stock_transfer_cancel",
    schema: actionSchema("stock_transfer_cancel"), effect: "record", receipt: "stock_transfer",
    title: "Cancel and return remaining transit stock", domain: "inventory", tool: "draftAction", policy: { roles: managers },
    scope: "store", clients: ["dashboard"], rollout: "source", procedures: ["inventory.transitionTransfer"],
    examples: ["Cancel and return remaining transit stock"], tests: ["packages/assistant/src/general/stock-transfer.test.ts"], brain,
  },
] as const satisfies readonly Capability[]

export type CapabilityId = (typeof capabilityManifest)[number]["id"]
export const writeCapabilities = capabilityManifest.filter(
  (capability): capability is Extract<typeof capability, WriteCapability> =>
    capability.mode === "write",
)
export function capabilityForAction(action: string) {
  const capability = writeCapabilities.find((entry) => entry.action === action)
  if (!capability) throw Error(`No capability for action ${action}`)
  return capability
}
