// Explicit product-owned vocabulary. Never derive event names from URLs or payloads.
export const dashboardProcedures = {
  "tenant.createBusiness": "business_setup",
  "tenant.createInventoryStore": "business_setup",
  "tenant.createStore": "business_setup",
  "setupAssistant.start": "assistant",
  "setupAssistant.begin": "assistant",
  "setupAssistant.skip": "assistant",
  "setupAssistant.finish": "assistant",
  "setupAssistant.updateEntity": "assistant",
  "setupAssistant.setEntityState": "assistant",
  "setupAssistant.removeEntities": "assistant",
  "setupAssistant.commit": "assistant",
  "catalog.setProductUsage": "catalog",
  "catalog.archiveOffering": "catalog",
  "catalog.archiveVariant": "catalog",
  "catalog.createUnitConfigurationDraft": "catalog",
  "catalog.createUnitDefinition": "catalog",
  "catalog.createSimpleItem": "catalog",
  "catalog.createItem": "catalog",
  "catalog.publishUnitConfiguration": "catalog",
  "catalog.setOfferingAvailability": "catalog",
  "catalog.updateUnitConfigurationDraft": "catalog",
  "catalog.photos.replace": "catalog",
  "catalog.photos.remove": "catalog",
  "catalog.photos.createIntent": "catalog",
  "catalog.categories.suggest": "catalog",
  "inventory.commitReservation": "inventory",
  "inventory.correctOperation": "inventory",
  "inventory.createCloseout": "inventory",
  "inventory.createStockCount": "inventory",
  "inventory.dispatchTransfer": "inventory",
  "inventory.finalizeCloseout": "inventory",
  "inventory.finalizeStockCount": "inventory",
  "inventory.moveCustody": "inventory",
  "inventory.postBalanceOperation": "inventory",
  "inventory.releaseReservation": "inventory",
  "inventory.reserveOffering": "inventory",
  "inventory.transformPackagedStock": "inventory",
  "inventory.transitionTransfer": "inventory",
  "orders.create": "sales",
  "orders.fulfillProductLine": "sales",
  "orders.fulfillChargeOnlyServiceLine": "sales",
  "orders.authorizeChargeOnlyServiceLine": "sales",
  "orders.fulfillProducts": "sales",
  "orders.returnProductLine": "sales",
  "orders.recordPayment": "payments",
  "prescriptions.refund": "payments",
  "customerLedger.refundUnusedCredit": "payments",
  "customers.create": "customers",
  "customerLedger.ensureAccount": "customers",
  "customerLedger.recordOpening": "customers",
  "customerLedger.recordReceipt": "customers",
  "customerLedger.applyCredit": "customers",
  "customerLedger.releaseAllocation": "customers",
  "customerLedger.reverseEntry": "customers",
  "finance.configureFiscalCalendar": "finance",
  "finance.registerPurchase": "finance",
  "finance.recognizePurchase": "finance",
  "finance.reversePurchaseRecognition": "finance",
  "finance.recordPurchase": "finance",
  "finance.payPurchase": "finance",
  "finance.reversePurchasePayment": "finance",
  "finance.allocateSupplierAdvance": "finance",
  "finance.releaseSupplierAllocation": "finance",
  "finance.createSupplier": "finance",
  "finance.recordSupplierOpening": "finance",
  "finance.recordSupplierAdvance": "finance",
  "finance.reverseSupplierEntry": "finance",
  "finance.reverseCashAdjustment": "finance",
  "finance.adjustCashCount": "finance",
  "finance.changePeriod": "finance",
  "finance.voidExpense": "finance",
  "finance.reverseBillPayment": "finance",
  "finance.recordCashCount": "finance",
  "finance.reverseMoney": "finance",
  "finance.createExpenseCategory": "finance",
  "finance.recordExpense": "finance",
  "finance.payBill": "finance",
  "finance.setup": "finance",
  "finance.createMoneyAccount": "finance",
  "finance.recordMoney": "finance",
  "finance.bankStatements.import": "finance",
  "finance.bankStatements.match": "finance",
  "finance.bankStatements.unmatch": "finance",
  "finance.expenseReceipts.attach": "finance",
  "finance.expenseReceipts.withdraw": "finance",
  "finance.expenseReceipts.createIntent": "finance",
  "retailOps.completeStaffOnboarding": "staff",
  "retailOps.updateStaffStatus": "staff",
  "retailOps.inviteStaff": "staff",
  "prescriptions.assignRole": "staff",
  "prescriptions.revokeRole": "staff",
  "domains.saveRegistrantProfile": "channels",
  "domains.checkAvailability": "channels",
  "domains.createCheckout": "channels",
  "domains.connectExternal": "channels",
  "domains.verifyConnection": "channels",
  "serviceCommerce.assignChannelAttendant": "channels",
  "serviceCommerce.completeChannelEmbeddedSignup": "channels",
  "serviceCommerce.publishCustomerEntryPoint": "channels",
  "serviceCommerce.retestCustomerChannelConnection": "channels",
  "serviceCommerce.revokeChannelAttendant": "channels",
  "serviceCommerce.revokeCustomerEntryPoint": "channels",
  "serviceCommerce.saveCustomerChannelBindings": "channels",
  "serviceCommerce.saveCustomerWhatsAppConnection": "channels",
  "serviceCommerce.setCustomerChannelConnectionLifecycle": "channels",
  "serviceCommerce.updateStoreConversationAvailabilitySchedule": "channels",
  "serviceCommerce.updateStoreConversationChannelMode": "channels",
  "prescriptions.connectWhatsAppManually": "channels",
  "prescriptions.retestWhatsAppConnection": "channels",
  "prescriptions.updateWhatsAppConnectionLifecycle": "channels",
  "prescriptions.suspendWhatsAppStoreBinding": "channels",
  "prescriptions.selectWhatsAppEmbeddedSignupNumber": "channels",
  "serviceCommerce.setStoreConversationManualPause": "conversations",
  "serviceCommerce.reportStoreConversation": "conversations",
  "serviceCommerce.acknowledgeStoreConversationStaffRead": "conversations",
  "serviceCommerce.requestStoreConversationAttachmentViewerGrant":
    "conversations",
  "serviceCommerce.claimStoreConversation": "conversations",
  "serviceCommerce.replyToStoreConversation": "conversations",
  "serviceCommerce.handoffStoreConversation": "conversations",
  "serviceCommerce.reassignStoreConversation": "conversations",
  "serviceCommerce.moderateStoreConversation": "conversations",
  "serviceCommerce.releaseStoreConversation": "conversations",
  "serviceCommerce.claimStoreConversationTransfer": "conversations",
  "prescriptions.updateRetentionPolicy": "prescriptions",
  "prescriptions.createPrivacyRequest": "prescriptions",
  "prescriptions.verifyPrivacyRequest": "prescriptions",
  "prescriptions.activateIncident": "prescriptions",
  "prescriptions.resolveIncident": "prescriptions",
  "prescriptions.approveManualDeliveryFee": "prescriptions",
  "prescriptions.upsertDeliveryZone": "prescriptions",
  "prescriptions.markPickupReady": "prescriptions",
  "prescriptions.handoffPickup": "prescriptions",
  "prescriptions.recordPickupException": "prescriptions",
  "prescriptions.assignDelivery": "prescriptions",
  "prescriptions.markDeliveryReady": "prescriptions",
  "prescriptions.transitionDelivery": "prescriptions",
  "prescriptions.uploadMedia": "prescriptions",
  "prescriptions.channel": "prescriptions",
  "prescriptions.staffIntake": "prescriptions",
  "prescriptions.requestClearerMedia": "prescriptions",
  "prescriptions.mediaAccess": "prescriptions",
  "prescriptions.startTranscription": "prescriptions",
  "prescriptions.verifyLine": "prescriptions",
  "prescriptions.reviseTranscription": "prescriptions",
  "prescriptions.submitForPharmacistReview": "prescriptions",
  "prescriptions.pharmacistReview": "prescriptions",
  "prescriptions.issueQuote": "prescriptions",
  "prescriptions.setActivation": "prescriptions",
  "prescriptions.updateSettings": "prescriptions",
  "services.addNote": "services",
  "services.assignJob": "services",
  "services.authorizeLine": "services",
  "services.batchUpdate": "services",
  "services.captureEvidence": "services",
  "services.confirmIntake": "services",
  "services.createAndConfirmIntake": "services",
  "services.createIntakeDraft": "services",
  "services.createRework": "services",
  "services.handoff": "services",
  "services.publishEvidence": "services",
  "services.recordException": "services",
  "services.rescheduleJob": "services",
  "services.revokeEvidence": "services",
  "services.splitLine": "services",
  "services.transitionLine": "services",
  "services.updateEvidenceUpload": "services",
  "services.updateSettings": "services",
  "serviceCommerce.setActivation": "services",
  "serviceCommerce.updateProfile": "services",
  "serviceCommerce.issueCustomerActions": "services",
  "serviceCommerce.createBookingCapability": "services",
  "serviceCommerce.createBookingResource": "services",
  "serviceCommerce.updateBookingConfiguration": "services",
  "serviceCommerce.confirmBooking": "services",
  "serviceCommerce.holdBookingSlot": "services",
  "serviceCommerce.reviseBooking": "services",
  "serviceCommerce.graduateCatalogOffering": "services",
  "serviceCommerce.publishCatalogOffering": "services",
  "serviceCommerce.attestCatalogAvailability": "services",
  "serviceCommerce.createCatalogDraft": "services",
  "serviceCommerce.linkCatalogOffering": "services",
  "serviceCommerce.promoteCatalogPrice": "services",
  "serviceCommerce.approveQuoteVersion": "services",
  "serviceCommerce.rejectQuoteVersion": "services",
  "serviceCommerce.updateQuoteReleaseSettings": "services",
  "serviceCommerce.deliveryFulfillment": "services",
  "serviceCommerce.pickupFulfillment": "services",
  "serviceCommerce.createInquiry": "services",
  "serviceCommerce.issueInquiryQuote": "services",
  "serviceCommerce.transitionInquiry": "services",
  "serviceCommerce.submitStaffIntake": "services",
  "serviceCommerce.commitMediaUpload": "services",
  "serviceCommerce.recordMediaSafety": "services",
  "serviceCommerce.requestMediaSafety": "services",
  "serviceCommerce.requestMediaViewerGrant": "services",
  "serviceCommerce.scheduleMediaRetry": "services",
  "serviceCommerce.verifyMediaObservation": "services",
  "serviceCommerce.revokePolicyDecision": "services",
  "serviceCommerce.setPolicyDecision": "services",
  "serviceAccess.createRequestForm": "services",
  "serviceAccess.createTracking": "services",
  "serviceAccess.issueQuote": "services",
  "serviceAccess.revokeTracking": "services",
  "serviceAccess.updateRequest": "services",
  "serviceCommunications.createBatchIntents": "services",
  "serviceCommunications.createIntent": "services",
  "serviceCommunications.recordDeliveryAttempt": "services",
  "serviceCommunications.recordManualShare": "services",
  "retailOps.createSubscriptionCheckoutIntent": "billing",
  "storeSubscriptions.prepareRefundReviewResponse": "billing",
  "storeSubscriptions.submitRefundReviewResponse": "billing",
  "orders.saveReceiptSettings": "settings",
  "orders.updateReminderSettings": "settings",
  "offline.updateSettings": "settings",
  "offline.registerDevice": "settings",
  "offline.review": "settings",
  "accountPrivacy.acceptLegalDocuments": "settings",
} as const
export type DashboardCategory =
  (typeof dashboardProcedures)[keyof typeof dashboardProcedures]
export type WorkflowPhase =
  | "started"
  | "completed"
  | "failed"
  | "blocked"
  | "cancelled"
  | "observed"
export type DashboardWorkflow = { category: string; action: string }
export function dashboardProcedure(path: string): DashboardWorkflow | null {
  if (!Object.hasOwn(dashboardProcedures, path)) return null
  const category = dashboardProcedures[path as keyof typeof dashboardProcedures]
  const action = path
    .split(".")
    .slice(1)
    .join("_")
    .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
    .replace(/store_conversation_/g, "conversation_")
  return { category, action }
}
export const dashboardBrowserActions = {
  login: { category: "access", action: "login" },
  logout: { category: "access", action: "logout" },
  signup: { category: "access", action: "signup" },
  signup_start: { category: "access", action: "signup_started" },
  verify_email: { category: "access", action: "verification_requested" },
  store_create: { category: "business_setup", action: "store_create" },
  business_switch: { category: "business_setup", action: "business_switch" },
  store_switch: { category: "business_setup", action: "store_switch" },
  staff_onboarding_code: {
    category: "staff",
    action: "onboarding_code_requested",
  },
  staff_onboarding: { category: "staff", action: "onboarding" },
  staff_invite: { category: "staff", action: "invite" },
  staff_update: { category: "staff", action: "update" },
  customer_create: { category: "customers", action: "create" },
  assistant_message: { category: "assistant", action: "message" },
  receipt_download: { category: "reports", action: "receipt_download" },
  finance_report_export: {
    category: "reports",
    action: "finance_report_export",
  },
  finance_statement_export: {
    category: "reports",
    action: "finance_statement_export",
  },
  finance_ledger_export: {
    category: "reports",
    action: "finance_ledger_export",
  },
  customer_statement_export: {
    category: "reports",
    action: "customer_statement_export",
  },
  expense_export: { category: "reports", action: "expense_export" },
  expense_receipt_download: {
    category: "reports",
    action: "expense_receipt_download",
  },
  channel_qr_download: { category: "channels", action: "qr_download" },
  prescription_privacy_export: {
    category: "prescriptions",
    action: "privacy_export",
  },
  report_print: { category: "reports", action: "print" },
  search: { category: "usability", action: "search" },
  filter: { category: "usability", action: "filter" },
  retry: { category: "usability", action: "retry" },
  empty_state: { category: "usability", action: "empty_state" },
} as const
export type DashboardBrowserAction = keyof typeof dashboardBrowserActions
export function workflowEvent(
  workflow: DashboardWorkflow,
  phase: WorkflowPhase,
) {
  return {
    name: `dashboard_${workflow.category}_${workflow.action}_${phase}`,
    properties: {
      surface: "dashboard",
      category: workflow.category,
      action: workflow.action,
      status: phase,
      success: phase === "completed",
    },
  }
}
export function workflowFailure(code?: string): "blocked" | "failed" {
  return [
    "UNAUTHORIZED",
    "FORBIDDEN",
    "PRECONDITION_FAILED",
    "CONFLICT",
    "TOO_MANY_REQUESTS",
  ].includes(code ?? "")
    ? "blocked"
    : "failed"
}
// A successful HTTP/RPC response can contain a partially failed setup batch.
export function procedureOutcome(
  path: string,
  output: unknown,
): { phase: WorkflowPhase; itemCount?: number } {
  if (path !== "setupAssistant.commit") return { phase: "completed" }
  if (!output || typeof output !== "object") return { phase: "failed" }
  const batch = output as { interrupted?: unknown; results?: unknown }
  if (!Array.isArray(batch.results)) return { phase: "failed" }
  const committed = batch.results.filter(
    (result) =>
      result && typeof result === "object" && result.state === "COMMITTED",
  ).length
  const failed = batch.results.some(
    (result) =>
      result && typeof result === "object" && result.state === "FAILED",
  )
  return {
    phase: batch.interrupted ? "blocked" : failed ? "failed" : "completed",
    itemCount: committed,
  }
}
