#!/usr/bin/env bun
import { mkdir, mkdtemp, readFile, realpath, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import path from "node:path"
import {
  MOBILE_PROJECT,
  MOBILE_TARGET,
} from "../.release/ewatrade-provider-bundle"
import type { ExpoPlatform } from "../.release/toolkit/bf26b05e442e122a9e9ef14cb6a8eff5a9d565d7/src/release/expo"
import type { ReleaseManifest } from "../.release/toolkit/bf26b05e442e122a9e9ef14cb6a8eff5a9d565d7/src/release/plan"
import type { NativeBuildConfiguration } from "./release-mobile-build-policy"
import {
  type NativeEnvironmentState,
  assertNativeEasEnvironment,
  nativeEnvironmentOverrides,
  resolveNativeEnvironment,
} from "./release-mobile-environment"
import {
  assertExpoConfigOwnership,
  declaredRuntimePolicy,
  parseExpoConfig,
  parseExpoFingerprint,
  parseResolvedRuntime,
  resolveRuntimeVersion,
} from "./release-mobile-runtime"
import {
  type CandidateCommand,
  type IsolatedCandidateExecutor,
  createSandboxContext,
  createSandboxExecExecutor,
} from "./release-mobile-sandbox"
import {
  assertCommittedToolchainInputs,
  assertConfigEnvironmentIsDeterministic,
  linkSnapshotDependencies,
  materializeCommittedMobileSnapshot,
  resolveWorkflow,
} from "./release-mobile-snapshot"
import { resolveExpoTools } from "./release-mobile-toolchain"
import {
  assertReleaseRevision,
  assertTrustedTopology,
  committedManifest,
  committedSourceFingerprints,
  dirtyReleaseInputs,
} from "./release-source"
export {
  type CandidateSandboxContext,
  type CandidateCommand,
  type IsolatedCandidateExecutor,
  buildCandidateSandboxProfile,
} from "./release-mobile-sandbox"
export { resolveTrustedRuntimeLibraries } from "./release-mobile-toolchain"
const SOURCE_STATE_VERSION = 1
const RELEASE_ENVIRONMENTS = ["preview", "production"] as const
const generatedStates = new WeakSet<object>()

export type MobileSourceEnvironment = (typeof RELEASE_ENVIRONMENTS)[number]

export type ExpoFingerprintAlgorithm = "sha1" | "sha256"

export type MobileSourceState = {
  version: 1
  revision: string
  environment: MobileSourceEnvironment
  sourceFingerprint: string
  nativeConfiguration: NativeBuildConfiguration
  nativeEnvironment: NativeEnvironmentState
  platforms: Record<
    ExpoPlatform,
    {
      fingerprint: string
      fingerprintAlgorithm: ExpoFingerprintAlgorithm
      runtimeVersion: string
    }
  >
}

export type GenerateMobileSourceStateInput = {
  repository: string
  revision: string
  environment: MobileSourceEnvironment
  /** Test seam. Production callers use the OS-enforced sandbox executor. */
  executor?: IsolatedCandidateExecutor
  /** Trusted toolchain override for tests; only the owned default can certify. */
  toolchainRepository?: string
  /** Test seam; an override cannot mint certified source authority. */
  nativeEnvironmentConfiguration?: NodeJS.ProcessEnv
}

/** True only for in-process state generated by the real OS-sandbox executor. */
export function isCertifiedMobileSourceState(
  value: unknown,
): value is MobileSourceState {
  return Boolean(
    value && typeof value === "object" && generatedStates.has(value),
  )
}

export async function generateMobileSourceState(
  input: GenerateMobileSourceStateInput,
): Promise<MobileSourceState> {
  if (!RELEASE_ENVIRONMENTS.includes(input.environment))
    throw new Error("Mobile source generation requires preview or production.")
  const repository = assertReleaseRevision(input.repository, input.revision)
  const manifest = committedManifest(repository, input.revision)
  const toolchainRepository = await realpath(
    input.toolchainRepository ?? path.resolve(import.meta.dir, ".."),
  )
  const trustedManifest = JSON.parse(
    await readFile(
      path.join(toolchainRepository, "release.manifest.json"),
      "utf8",
    ),
  ) as ReleaseManifest
  assertTrustedTopology(manifest, trustedManifest)
  const mobileManifest = {
    ...manifest,
    targets: manifest.targets.filter(
      (target) => target.id === MOBILE_TARGET.targetId,
    ),
  }
  if (!mobileManifest.targets.length)
    throw new Error("Committed release manifest has no mobile target.")
  const dirty = dirtyReleaseInputs(repository, mobileManifest)
  if (dirty.length)
    throw new Error(
      `Commit or remove changed mobile release inputs before fingerprinting: ${dirty.join(", ")}`,
    )

  const sourceFingerprint = committedSourceFingerprints(
    repository,
    input.revision,
    mobileManifest,
  ).mobile
  if (!sourceFingerprint || !/^[0-9a-f]{64}$/i.test(sourceFingerprint))
    throw new Error("Committed mobile source fingerprint is unavailable.")

  const nativeEnvironment = resolveNativeEnvironment(
    {
      revision: input.revision,
      environment: input.environment,
      sourceFingerprint,
    },
    input.nativeEnvironmentConfiguration,
  )

  const tools = await resolveExpoTools(toolchainRepository)
  const tempRoot = await mkdtemp(path.join(tmpdir(), "ewatrade-mobile-source-"))
  const snapshotRoot = path.join(tempRoot, "snapshot")
  const projectRoot = path.join(snapshotRoot, "apps/mobile")
  const home = path.join(tempRoot, "home")
  const privateTemp = path.join(tempRoot, "tmp")
  await Promise.all([
    mkdir(snapshotRoot, { recursive: true, mode: 0o700 }),
    mkdir(home, { recursive: true, mode: 0o700 }),
    mkdir(privateTemp, { recursive: true, mode: 0o700 }),
  ])

  try {
    await materializeCommittedMobileSnapshot(
      repository,
      input.revision,
      mobileManifest,
      snapshotRoot,
    )
    await assertCommittedToolchainInputs(snapshotRoot, toolchainRepository)
    assertNativeEasEnvironment(
      JSON.parse(await readFile(path.join(projectRoot, "eas.json"), "utf8")),
      input.environment,
      nativeEnvironment.values,
    )
    await assertConfigEnvironmentIsDeterministic(
      projectRoot,
      nativeEnvironment.state.keys,
    )
    if (!input.executor)
      await linkSnapshotDependencies(
        toolchainRepository,
        snapshotRoot,
        projectRoot,
        tools.mobileNodeModules,
      )
    const executor = input.executor ?? createSandboxExecExecutor()
    const context = await createSandboxContext({
      snapshotRoot,
      projectRoot,
      home,
      temp: privateTemp,
      dependencyStore: tools.dependencyStore,
      nodeBinary: tools.nodeBinary,
      gitBinary: tools.gitBinary,
      runtimeLibraries: tools.runtimeLibraries,
      environment: {
        ...safeCandidateEnvironment(
          input.environment,
          home,
          privateTemp,
          tools.nodeBinary,
        ),
        ...nativeEnvironmentOverrides(nativeEnvironment.values),
      },
    })
    await executor.probe(context)

    const expoConfigCommand: CandidateCommand = {
      label: "expo-config",
      executable: tools.nodeBinary,
      args: [tools.expoCli, "config", "--json"],
    }
    const configText = await executor.execute(expoConfigCommand, context)
    const config = parseExpoConfig(configText)
    assertExpoConfigOwnership(config, MOBILE_PROJECT)
    const platformResults = {} as MobileSourceState["platforms"]
    for (const platform of MOBILE_TARGET.platforms) {
      const workflow = resolveWorkflow(repository, input.revision, platform)
      const command: CandidateCommand = {
        label:
          platform === "android"
            ? "expo-fingerprint-android"
            : "expo-fingerprint-ios",
        executable: tools.nodeBinary,
        args: [
          tools.expoUpdatesCli,
          "fingerprint:generate",
          "--platform",
          platform,
          "--workflow",
          workflow,
        ],
      }
      const fingerprint = parseExpoFingerprint(
        await executor.execute(command, context),
        platform,
      )
      const runtimeVersion = parseResolvedRuntime(
        await executor.execute(
          {
            label:
              platform === "android"
                ? "expo-runtime-android"
                : "expo-runtime-ios",
            executable: tools.nodeBinary,
            args: [
              tools.expoUpdatesCli,
              "runtimeversion:resolve",
              "--platform",
              platform,
              "--workflow",
              workflow,
            ],
          },
          context,
        ),
        platform,
        workflow,
      )
      if (
        runtimeVersion !== resolveRuntimeVersion(config, platform, fingerprint)
      )
        throw new Error(
          `${platform}: independently resolved runtime disagrees with the source fingerprint/config.`,
        )
      platformResults[platform] = {
        fingerprint,
        fingerprintAlgorithm: fingerprint.length === 40 ? "sha1" : "sha256",
        runtimeVersion,
      }
    }

    const result: MobileSourceState = {
      version: SOURCE_STATE_VERSION,
      revision: input.revision,
      environment: input.environment,
      sourceFingerprint,
      nativeEnvironment: nativeEnvironment.state,
      nativeConfiguration: {
        appVersion: typeof config.version === "string" ? config.version : null,
        runtimePolicies: {
          android: declaredRuntimePolicy(config, "android"),
          ios: declaredRuntimePolicy(config, "ios"),
        },
      },
      platforms: platformResults,
    }
    deepFreeze(result)
    if (
      !input.executor &&
      !input.nativeEnvironmentConfiguration &&
      toolchainRepository ===
        (await realpath(path.resolve(import.meta.dir, "..")))
    )
      generatedStates.add(result)
    return result
  } finally {
    await rm(tempRoot, { recursive: true, force: true })
  }
}

export function safeCandidateEnvironment(
  environment: MobileSourceEnvironment,
  home: string,
  temp: string,
  nodeBinary = process.execPath,
): NodeJS.ProcessEnv {
  return {
    PATH: `${path.dirname(nodeBinary)}:/usr/bin:/bin`,
    HOME: home,
    TMPDIR: temp,
    CI: "1",
    NO_COLOR: "1",
    EXPO_NO_DOTENV: "1",
    EXPO_OFFLINE: "1",
    APP_ENV: environment,
    APP_VARIANT: environment,
    EXPO_PUBLIC_APP_VARIANT: environment,
    EAS_BUILD_PROFILE: environment,
  }
}

function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== "object" || Object.isFrozen(value))
    return value
  Object.freeze(value)
  for (const child of Object.values(value as Record<string, unknown>))
    deepFreeze(child)
  return value
}

async function main() {
  const args = Bun.argv.slice(2)
  if (
    args.length !== 6 ||
    args[0] !== "--env" ||
    !RELEASE_ENVIRONMENTS.includes(args[1] as MobileSourceEnvironment) ||
    args[2] !== "--repo" ||
    args[4] !== "--revision" ||
    !args[3] ||
    !args[5]
  )
    throw new Error(
      "Use --env preview|production --repo <candidate root> --revision <full committed SHA>.",
    )
  const sourceState = await generateMobileSourceState({
    repository: args[3],
    environment: args[1] as MobileSourceEnvironment,
    revision: args[5],
  })
  process.stdout.write(`${JSON.stringify(sourceState)}\n`)
}
if (import.meta.main) {
  main().catch((error) => {
    console.error(
      error instanceof Error
        ? error.message
        : "Credential-free Expo source generation failed closed.",
    )
    process.exitCode = 2
  })
}
