"use strict";
const icons={
home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
order:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 7h6M9 11h6M9 15h4"/>',
catalog:'<path d="m3 8 9-5 9 5v13H3z"/><path d="M7 21V10h10v11M9 14h6M9 17h6"/>',
plus:'<path d="M12 5v14M5 12h14"/>',
more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',
sync:'<path d="M20 7a9 9 0 0 0-15-2L3 7M3 3v4h4M4 17a9 9 0 0 0 15 2l2-2M17 17h4v4"/>',
chevron:'<path d="m9 5 7 7-7 7"/>',down:'<path d="m6 9 6 6 6-6"/>',
arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',
team:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 4v3"/>',
wrench:'<path d="M14 6a5 5 0 0 0-7 7L3 17a3 3 0 0 0 4 4l4-4a5 5 0 0 0 7-7l-3 3-4-4z"/>',
signal:'<path d="M4 19v-3M9 19v-7M14 19V8M19 19V4"/>',wifi:'<path d="M3 8a15 15 0 0 1 18 0M6 12a10 10 0 0 1 12 0M9 16a5 5 0 0 1 6 0M12 20h.01"/>',battery:'<rect x="3" y="7" width="16" height="10" rx="2"/><path d="M21 10v4M6 10h10v4H6z"/>'
};
const icon=n=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(icons[n]||icons.order)+'</svg>';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>"R"+(n/100).toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2});
const stages=[
{id:"01",name:"A fresh business",subtitle:"Nothing to sell yet. Start with one item.",catalog:"empty",history:false,team:"none",rule:"resolved · no catalog · no order history",note:"One useful task replaces a dashboard of zeros. Team setup stays a secondary, optional route."},
{id:"02",name:"Finish the first item",subtitle:"An item exists, but it is not sellable yet.",catalog:"unfinished",history:false,team:"none",rule:"resolved · catalog exists · no active sellable item",note:"Resume the existing item instead of asking the owner to start again. Readiness depends on availability, active status and a fixed price."},
{id:"03",name:"Ready for an order",subtitle:"The catalog is ready. Now put it to work.",catalog:"ready",history:false,team:"none",rule:"resolved · active sellable item · no order history",note:"A completed catalog step gives confidence. The first-order action takes over. Financial facts wait for actual activity."},
{id:"04",name:"The first order is in",subtitle:"Facts appear. Team setup becomes a small nudge.",catalog:"ready",history:true,team:"none",rule:"resolved · order history · optional team not dismissed",note:"The familiar 01 layout begins to emerge. The order stays central; the optional team panel can be dismissed by a solo owner."},
{id:"05",name:"An invitation is pending",subtitle:"Keep selling while someone joins.",catalog:"ready",history:true,team:"pending",rule:"resolved · order history · directory confirms pending invite",note:"A quiet pending acknowledgement replaces the invitation prompt. It does not claim email delivery or acceptance. No resend action."},
{id:"06",name:"Everyday Clear Counter",subtitle:"The final 01 Home, with guidance out of the way.",catalog:"ready",history:true,team:"active",rule:"resolved · order history · active team OR team nudge dismissed",note:"New order, compact facts, recent orders and utilities. A solo business reaches this same Home without inviting anyone."},
{id:"07",name:"A quiet returning day",subtitle:"No recent rows. The business is still established.",catalog:"ready",history:true,team:"solo",emptySlice:true,branch:true,rule:"hasOrders = true · loaded orders = []",note:"Keep New order and See all orders. Describe the empty loaded list accurately; never restart first-order setup from recent-row count."},
{id:"08",name:"Status is unavailable",subtitle:"Unknown signals should not become false zeros.",catalog:"empty",history:false,team:"none",resolved:false,branch:true,rule:"availability unresolved / unavailable",note:"Show recovery instead of asserting no items, no orders or no staff. Native implementation must preserve loading, cache and offline distinctions."}
];
const sampleOrders=[{id:"S-001",customer:"Sample customer A",totalMinor:45000,label:"Consultation"},{id:"S-002",customer:"Sample customer B",totalMinor:25000,label:"Setup service"}];
function seed(stage){return{catalog:stage.catalog,history:stage.history,team:stage.team,resolved:stage.resolved!==false,orders:stage.history&&!stage.emptySlice?structuredClone(sampleOrders.slice(0,stage.id==="04"||stage.id==="05"?1:2)):[],item:stage.catalog==="empty"?"":"Consultation",member:stage.team==="pending"?"Sample team member":"",sequence:0,drafts:{item:"",customer:"",value:"",member:"",email:""}};}
const params=new URLSearchParams(location.search);let theme=params.get("theme")==="dark"?"dark":"light",largeText=params.get("text")==="200",selected=null,live=seed(stages[0]),context=null;
document.body.classList.toggle("capture",params.get("capture")==="1");
function action(name,label,ic,cls="primary-button"){return '<button class="'+cls+'" data-action="'+name+'">'+(ic?icon(ic):'')+'<span>'+label+'</span></button>';}
function row(name,label,ic,detail){return '<button class="action-row" data-action="'+name+'"><span class="row-icon">'+icon(ic)+'</span><span>'+label+(detail?'<span class="row-detail">'+detail+'</span>':'')+'</span>'+icon("chevron")+'</button>';}
function header(){return '<header class="phone-header"><button class="avatar" data-action="profile" aria-label="Ishaq profile">I</button><div class="identity"><p class="greeting">Hello, Ishaq</p><button class="business-button" data-action="business" aria-label="Switch Business, Jawdah">Jawdah '+icon("down")+'</button></div><div class="header-tools"><button class="icon-button" data-action="sync" aria-label="Open sync status">'+icon("sync")+'</button><button class="icon-button" data-action="search" aria-label="Open global search">'+icon("search")+'</button></div></header>';}
function dock(){return '<nav class="dock" aria-label="Main navigation">'+[["home","Home","home"],["orders","Orders","order"],["create","Create","plus"],["catalog","Products","catalog"],["more","More","more"]].map(([name,label,ic])=>'<button class="nav-button '+(name==="create"?'create':'')+'" data-action="'+name+'" '+(name==="home"?'aria-current="page"':'')+'>'+icon(ic)+'<span>'+label+'</span></button>').join('')+'</nav><div class="android-gesture" aria-hidden="true"></div>';}
function path(s){return '<div class="path-list" aria-label="Getting started tasks">'+[["Add a Product or Service",s.catalog==="ready"?'Your catalog is ready.':s.catalog==="unfinished"?'Finish making your item sellable.':'Choose one thing your customers can buy.',s.catalog==="ready",s.catalog!=="ready"],["Take your first order",s.catalog==="ready"?'Ready whenever your customer is.':'After your catalog is ready.',false,s.catalog==="ready"],["Bring your team along",s.team==="active"?'Team already set up.':s.team==="pending"?'Invitation pending.':'Optional · whenever you need a hand.',s.team==="active",false]].map(([title,copy,done,current],i)=>'<div class="path-row '+(done?'done':current?'current':'')+'"><span class="path-dot">'+(done?icon("check"):i+1)+'</span><div class="path-copy"><strong>'+title+'</strong><p>'+copy+'</p></div></div>').join('')+'</div>';}
function facts(s){return '<div class="facts"><div class="fact"><span class="fact-top">'+icon("catalog")+'Catalog</span><strong class="fact-value">'+(s.catalog==="ready"?'Ready':'Not ready')+'</strong></div><div class="fact"><span class="fact-top">'+icon("order")+'Recent orders</span><strong class="fact-value">'+s.orders.length+'</strong></div></div><div class="revenue"><span class="small-label">Recent revenue</span><strong class="fact-value">'+money(s.orders.reduce((sum,o)=>sum+o.totalMinor,0))+'</strong><p>Across '+s.orders.length+' loaded '+(s.orders.length===1?'order':'orders')+'</p></div>';}
function orderRows(s){return s.orders.slice(0,2).map(o=>'<button class="order-row" data-action="order-detail" data-order="'+esc(o.id)+'"><span class="order-avatar">'+esc(o.customer.split(' ').map(x=>x[0]).slice(0,2).join(''))+'</span><span><span class="order-name">'+esc(o.customer)+'</span><span class="order-meta">'+esc(o.id)+' · '+esc(o.label)+'</span></span><span class="order-right">'+money(o.totalMinor)+'<span class="status-label">Recorded</span></span></button>').join('');}
function orders(s){return '<div class="section-heading"><h3>Recent orders</h3>'+action("orders","See all",null,"text-button")+'</div>'+(s.orders.length?orderRows(s):'<div class="empty-orders">'+icon("order")+'<strong>No recent orders to show</strong><p>Your order history is still available.</p>'+action("orders","See all orders",null,"text-button")+'</div>');}
function pending(s){return '<div class="pending-note">'+icon("team")+'<div><strong>Invitation pending</strong><p>'+esc(s.member||'Sample team member')+' has not joined yet.</p></div></div>';}
function home(s){if(!s.resolved)return '<div class="phone-body"><p class="phone-kicker">YOUR BUSINESS</p><h2 class="phone-title">Let’s get you up to date.</h2><div class="unknown-box">'+icon("sync")+'<h3>Business status unavailable</h3><p>We couldn’t confirm your store’s setup or recent activity. Try again to load your Home.</p>'+action("retry","Try again","sync")+'</div>'+row("catalog","Open your catalog","catalog")+row("orders","Open order history","order")+'</div>';
let body='<div class="phone-body">';
if(!s.history){const ready=s.catalog==="ready",unfinished=s.catalog==="unfinished";body+='<div class="setup-context"><p class="phone-kicker">GETTING STARTED</p><span class="setup-count">'+(ready?'1 of 2':'0 of 2')+' essentials complete</span></div><h2 class="phone-title">'+(ready?'Ready for your first order.':unfinished?'Let’s finish your catalog.':'Let’s get your business ready.')+'</h2><p class="phone-subtitle">'+(ready?'You have something to sell. Let’s record your first customer order.':unfinished?'Your item is here. Make it available for customers to buy.':'Start small. Add one Product or Service your customers can buy.')+'</p><div class="next-card"><div class="next-icon">'+icon(ready?'order':'catalog')+'</div><h3>'+(ready?'Take your first order':unfinished?'Make your item sellable':'Add your first item')+'</h3><p>'+(ready?'Choose the item and record what your customer is buying.':unfinished?'Check its price, active status and store availability.':'Choose a Product or Service, give it a name and set a price.')+'</p>'+action(ready?'order':'item',ready?'Create an order':unfinished?'Finish item setup':'Add a Product or Service','plus')+'</div>'+path(s)+(s.team==="pending"?pending(s):s.team==="active"?row("team","View your team","team"):row("team","Invite your team","team","Optional · do this whenever you’re ready"))+row("catalog",ready?'View your catalog':'Open your catalog','catalog');
}else{body+='<button class="sync-note" data-action="sync">'+icon("check")+'Synced now</button><h2 class="phone-title">Your store, at a glance.</h2><p class="phone-subtitle">'+(s.catalog==="ready"?'Create an order or catch up on recent activity.':'Get your catalog ready to take another order.')+'</p>'+action(s.catalog==="ready"?'order':'item',s.catalog==="ready"?'New order':'Get catalog ready','plus')+facts(s)+orders(s);
if(s.team==="none")body+='<div class="optional-panel"><p class="phone-kicker">WHEN YOU NEED A HAND</p><h3>Share the work with your team.</h3><p>You can invite someone now or keep running your business on your own.</p><div class="optional-actions">'+action("team","Invite someone",null,"")+action("solo","I work on my own",null,"")+'</div></div>';
if(s.team==="pending")body+=pending(s);
body+='<div class="section-heading"><h3>Store shortcuts</h3></div>'+row("catalog","View your catalog","catalog")+row("team",s.team==="active"?'View your team':s.team==="pending"?'View invitation':'Invite your team','team',s.team==="solo"?'Optional':'');}
return body+'</div>';}
function phone(s,t,id){return '<div class="device d01 '+(largeText?'large-text':'')+'" data-stage="'+id+'" data-theme="'+t+'" aria-label="'+(id==="live"?'Connected journey':'State '+id)+', '+t+', Android Home preview"><div class="camera-dot" aria-hidden="true"></div><div class="status-bar" aria-hidden="true"><span>9:18</span><div class="status-symbols">'+icon("signal")+icon("wifi")+icon("battery")+'</div></div><div class="screen-scroll">'+header()+home(s)+'</div>'+dock()+'</div>';}
function classify(s){if(!s.resolved)return stages[7];if(!s.history)return stages[s.catalog==="empty"?0:s.catalog==="unfinished"?1:2];if(!s.orders.length)return stages[6];return stages[s.team==="none"?3:s.team==="pending"?4:5];}
function inspector(){return '<div class="signal-controls"><label>Catalog readiness<select id="catalog-signal"><option value="empty">No catalog</option><option value="unfinished">Catalog exists · not sellable</option><option value="ready">Sellable item available</option></select></label><label>Order history<select id="history-signal"><option value="no">No orders ever</option><option value="yes">Orders exist</option></select></label><label>Loaded order list<select id="slice-signal"><option value="empty">Empty loaded list</option><option value="sample">Load two sample rows</option></select></label><label>Team state<select id="team-signal"><option value="none">No team · prompt available</option><option value="pending">Invitation pending</option><option value="active">Active team</option><option value="solo">Solo · prompt dismissed</option></select></label><label>Business status<select id="resolved-signal"><option value="yes">Resolved</option><option value="no">Unavailable / unknown</option></select></label><button id="accept-invite" '+(live.team!=="pending"?'disabled':'')+'>Simulate invitation acceptance</button><p class="inspector-note">These controls are outside the product. Pending/active team needs directory data; hasStaff alone does not prove acceptance. This journey is an owner view.</p></div>';}
function render(){const pos=new Map([...document.querySelectorAll('.device')].map(d=>[d.dataset.stage+d.dataset.theme,d.querySelector('.screen-scroll').scrollTop]));document.querySelector('#board').innerHTML=stages.map(d=>'<article class="journey-card"><p class="direction-number">'+(d.branch?'BRANCH':'STAGE')+' '+d.id+(d.branch?'<span class="branch-tag">STATE RECOVERY</span>':'')+'</p><h2>'+d.name+'</h2><p class="direction-subtitle">'+d.subtitle+'</p><div class="mini-stage">'+phone(seed(d),theme,d.id)+'</div><a class="review-link" href="#stage-'+d.id+'">Explore '+d.id+' in Light + Dark →</a><p class="tradeoff">'+d.note+'</p></article>').join('');
if(selected){const d=classify(live);document.querySelector('#detail').innerHTML='<div class="detail-heading"><div><p class="eyebrow">01 CLEAR COUNTER · '+(selected==='try'?'CONNECTED JOURNEY':'STATE '+selected)+'</p><h2>'+d.name+'</h2></div><a class="back-button" href="#board">← All journey states</a></div><div class="detail-layout"><div class="pair">'+['light','dark'].map(t=>'<div class="full-preview"><p class="theme-preview-label">'+t.toUpperCase()+'<span>390 × 844 · scroll inside phone</span></p>'+phone(live,t,'live')+'</div>').join('')+'</div><aside class="detail-notes"><h3>'+d.subtitle+'</h3><p>'+d.note+'</p><p class="state-rule">'+d.rule+'</p><h3>Try another business state</h3>'+inspector()+'</aside></div><nav class="sequence-nav" aria-label="Journey stages">'+stages.map(d=>'<a href="#stage-'+d.id+'">'+d.id+' '+d.name+'</a>').join('')+'</nav>';for(const[id,value]of [['catalog',live.catalog],['history',live.history?'yes':'no'],['slice',live.orders.length?'sample':'empty'],['team',live.team],['resolved',live.resolved?'yes':'no']])document.querySelector('#'+id+'-signal').value=value;}
document.querySelector('#board').hidden=!!selected;document.querySelector('#detail').hidden=!selected;document.querySelectorAll('.device').forEach(d=>d.querySelector('.screen-scroll').scrollTop=pos.get(d.dataset.stage+d.dataset.theme)||0);document.querySelectorAll('.segmented [data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===theme)));document.querySelector('#text-control').setAttribute('aria-pressed',String(largeText));document.querySelector('#text-control').textContent=largeText?'200% → 100%':'100% → 200%';}
function announce(message){document.querySelector('#announcement').textContent=message;}
function route(){const match=location.hash.match(/^#stage-(0[1-8])$/);selected=match?match[1]:location.hash==='#try'?'try':null;if(match)live=seed(stages.find(s=>s.id===selected));render();if(selected)document.querySelector('#detail').scrollIntoView({block:'start'});}
function dialog(title,content){const d=document.querySelector('#preview-dialog');d.dataset.theme=context?.theme||theme;document.querySelector('#dialog-body').innerHTML='<h2 id="dialog-title">'+title+'</h2>'+content;if(!d.open)d.showModal();(d.querySelector('input')||d.querySelector('#close-dialog')).focus();}
function openItem(){const draft=live.drafts.item||live.item;dialog(live.catalog==='empty'?'Add your first item':'Finish item setup','<p>Simplified editor for testing how Home changes. The native item editor retains its full validation.</p><form id="item-form"><label for="item-name">Product or Service name</label><input id="item-name" name="item" required maxlength="100" value="'+esc(draft)+'" placeholder="Consultation" autocomplete="off"><label for="item-kind">Item type</label><select id="item-kind" name="kind"><option>Service</option><option>Product</option></select><label for="item-outcome">Preview outcome</label><select id="item-outcome" name="outcome"><option value="ready">Active, priced and available to sell</option><option value="unfinished">Saved, but not yet sellable</option></select><p class="form-error" id="item-error" role="alert"></p><button class="primary-button" type="submit">Save preview item</button></form>');}
function handle(name,element){switch(name){case'item':openItem();break;case'order':if(!live.resolved){dialog('Confirm your business status','<p>Load business status before choosing the next order action.</p>'+action('retry','Try again','sync'));break;}if(live.catalog!=='ready'){openItem();break;}dialog(live.history?'New order':'Your first order','<p>Your sellable item is '+esc(live.item||'Consultation')+'. Record a sample order to reveal the next Home state.</p><form id="order-form"><label for="customer-name">Customer name</label><input id="customer-name" name="customer" required maxlength="80" value="'+esc(live.drafts.customer)+'" placeholder="Sample customer" autocomplete="off"><label for="order-value">Order value (R)</label><input id="order-value" name="value" required inputmode="decimal" value="'+esc(live.drafts.value)+'" placeholder="450.00" autocomplete="off"><p class="form-error" id="order-error" role="alert"></p><button class="primary-button" type="submit">Create preview order</button></form>');break;
case'team':if(live.team==='pending'){dialog('Invitation pending','<p><b>'+esc(live.member||'Sample team member')+'</b> has not joined yet.</p><p>Acceptance can be simulated using the workshop controls. Membership presence does not prove email delivery.</p>');break;}if(live.team==='active'){dialog('Your team','<p>Sample team member · Cashier · Active</p><p>This preview shows one illustrative staff member.</p>');break;}dialog('Invite someone to help','<p>Team setup is optional. Prepare a local fixture to see the pending Home state.</p><form id="team-form"><label for="member-name">Name (optional)</label><input id="member-name" name="member" maxlength="120" value="'+esc(live.drafts.member)+'" placeholder="Sample team member" autocomplete="off"><label for="member-email">Email address</label><input id="member-email" name="email" type="email" required maxlength="320" value="'+esc(live.drafts.email)+'" placeholder="someone@example.com" autocomplete="off"><p>Role: Cashier</p><button class="primary-button" type="submit">Create preview invitation</button></form>');break;
case'solo':live.team='solo';render();announce('Optional team prompt dismissed. Everyday Home is available to a solo business.');break;
case'retry':live.resolved=true;document.querySelector('#preview-dialog').close();render();announce('Preview business status loaded.');break;
case'catalog':dialog('Your catalog',!live.resolved?'<p>Catalog data is not loaded in this fixture.</p>':live.catalog==='empty'?'<p>No catalog items yet.</p>'+action('item','Add a Product or Service','plus'):'<p><b>'+esc(live.item||'Consultation')+'</b></p><p>'+(live.catalog==='ready'?'Active, priced and available to sell.':'Not sellable yet. Check price, active status and availability.')+'</p>'+action('item',live.catalog==='ready'?'Edit item':'Finish item setup','catalog'));break;
case'orders':dialog('Order history',!live.resolved?'<p>Order data is not loaded in this fixture.</p>':live.orders.length?'<p>Latest '+live.orders.length+' loaded orders · '+money(live.orders.reduce((n,o)=>n+o.totalMinor,0))+' total value</p>'+orderRows(live):live.history?'<p>No recent rows in this fixture. Earlier order history exists.</p><p>The native action opens the full order history; this workshop does not invent older records.</p>':'<p>You haven’t recorded an order yet.</p>'+action(live.catalog==='ready'?'order':'item',live.catalog==='ready'?'Create your first order':'Add an item first','plus'));break;
case'order-detail':{const o=live.orders.find(o=>o.id===element.dataset.order);if(o)dialog('Order '+esc(o.id),'<p><b>'+esc(o.customer)+'</b></p><p>'+esc(o.label)+'</p><div class="ledger-line"><span>Order value</span><strong>'+money(o.totalMinor)+'</strong></div><p>This value contributes to Recent revenue across loaded orders.</p>');break;}
case'create':dialog('Create',row('order','Order','order')+row('item','Product or Service','catalog')+row('team','Staff invitation','team','Optional'));break;
case'search':dialog('Search Jawdah','<label for="search-input">Search local orders and catalog</label><input id="search-input" autocomplete="off" placeholder="Customer, order or item"><div id="search-results"><p>Enter a name to search the current preview.</p></div>');break;
case'sync':dialog('Sync status','<p>'+(live.resolved?'Synced now':'Business status unavailable')+'</p><p>Preview only. Native sync retains queued operations, cache and offline states.</p>');break;
case'profile':dialog('Ishaq','<p>Owner · Jawdah</p>');break;
case'business':dialog('Switch Business','<p>Jawdah · currently selected</p>');break;
case'more':dialog('More',row('team',live.team==='active'?'View team':'Team setup','team')+row('sync','Sync status','sync')+row('business','Switch Business','catalog'));break;
case'home':document.querySelector('#preview-dialog').close();break;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='close-dialog'){document.querySelector('#preview-dialog').close();return;}if(b.id==='text-control'){largeText=!largeText;render();return;}if(b.id==='reset-control'){document.querySelector('#preview-dialog').close();live=seed(stages[0]);theme='light';largeText=false;context=null;selected=null;location.hash='board';document.querySelectorAll('.screen-scroll').forEach(e=>e.scrollTop=0);render();announce('All journey states, drafts and controls reset.');return;}if(b.closest('.segmented')&&b.dataset.theme){theme=b.dataset.theme;render();return;}if(b.id==='accept-invite'){live.team='active';render();announce('Workshop simulated acceptance; no real invitation was sent.');return;}if(b.dataset.action){const device=b.closest('.device');if(device){context={theme:device.dataset.theme,action:b.dataset.action};if(device.dataset.stage!=='live'){live=seed(stages.find(s=>s.id===device.dataset.stage));selected='try';history.replaceState(null,'','#try');render();}}handle(b.dataset.action,b);}});
document.addEventListener('change',e=>{if(!e.target.id.endsWith('-signal'))return;switch(e.target.id){case'catalog-signal':live.catalog=e.target.value;if(live.catalog==='empty')live.item='';else live.item||='Consultation';break;case'history-signal':live.history=e.target.value==='yes';if(!live.history)live.orders=[];break;case'slice-signal':live.orders=e.target.value==='sample'?structuredClone(sampleOrders):[];if(live.orders.length)live.history=true;break;case'team-signal':live.team=e.target.value;break;case'resolved-signal':live.resolved=e.target.value==='yes';break;}render();announce('Business signals changed independently.');});
document.addEventListener('input',e=>{const fields={'item-name':'item','customer-name':'customer','order-value':'value','member-name':'member','member-email':'email'};if(fields[e.target.id])live.drafts[fields[e.target.id]]=e.target.value;if(e.target.id==='search-input'){const q=e.target.value.trim().toLowerCase();const results=live.orders.filter(o=>(o.id+' '+o.customer+' '+o.label).toLowerCase().includes(q));const item=live.item&&live.item.toLowerCase().includes(q);document.querySelector('#search-results').innerHTML=q?(results.length||item?orderRows({...live,orders:results})+(item?'<p>'+esc(live.item)+'</p>':''):'<p>No matching local records.</p>'):'<p>Enter a name to search the current preview.</p>';}});
document.addEventListener('submit',e=>{if(!e.target.matches('#item-form,#order-form,#team-form'))return;e.preventDefault();const data=new FormData(e.target);if(e.target.id==='item-form'){const item=String(data.get('item')).trim();if(!item){document.querySelector('#item-error').textContent='Enter an item name.';return;}live.item=item;live.catalog=String(data.get('outcome'));live.drafts.item='';}else if(e.target.id==='order-form'){const customer=String(data.get('customer')).trim(),value=String(data.get('value')).trim();if(!customer||!/^\d{1,7}(\.\d{1,2})?$/.test(value)||Number(value)<=0){document.querySelector('#order-error').textContent='Enter a customer and a positive value with up to two decimal places.';return;}const [whole,fraction='']=value.split('.');live.sequence++;live.orders.unshift({id:'P-'+String(live.sequence).padStart(3,'0'),customer,totalMinor:Number(whole)*100+Number(fraction.padEnd(2,'0')),label:live.item||'Catalog item'});live.orders=live.orders.slice(0,8);live.history=true;live.drafts.customer='';live.drafts.value='';}else{live.member=String(data.get('member')).trim()||String(data.get('email')).trim();live.team='pending';live.drafts.member='';live.drafts.email='';}document.querySelector('#preview-dialog').close();render();announce('Local preview updated. Home now shows '+classify(live).name+'.');});
document.querySelector('#preview-dialog').addEventListener('close',()=>{if(context){const device=[...document.querySelectorAll('#detail .device')].find(d=>d.dataset.theme===context.theme);device?.querySelector('[data-action="'+context.action+'"]')?.focus({preventScroll:true});}});
window.addEventListener('hashchange',route);route();
