const stages=[['fresh','Fresh workspace'],['unfinished','First item unfinished'],['ready','Ready for first order'],['first','First order recorded'],['pending','Invitation pending'],['everyday','Everyday workspace'],['returning','Returning · no recent rows'],['unavailable','Status unavailable']];
const options=[['01','Clear workspace','A calm next action, with the setup path kept in view.','Closest to the accepted mobile direction. Spacious guidance becomes a compact operating header.'],['02','Guided desk','An explicit task list beside the working area.','More guidance stays visible. Better for owners who want to see what is complete and what comes next.'],['03','Open workspace','A prominent next step and visible workspace entry points.','More exploratory. Products, sales and team appear as places to work, with stronger visual hierarchy.']];
let theme='light',stage='fresh';const gallery=document.querySelector('.gallery');
for(const [id,name,sub,trade] of options){const card=document.createElement('article');card.className='direction-card';card.innerHTML='<div class="direction-meta"><span>'+id+'</span>'+(id==='01'?'<span class="recommend">Suggested starting point</span>':'')+'</div><h2>'+name+'</h2><p class="direction-copy">'+sub+'</p><div class="frame-wrap"><iframe title="'+id+' '+name+' interactive preview" src="screen.html?option='+id+'&stage=fresh&embed=1"></iframe></div><a class="open-direction" href="screen.html?option='+id+'" target="_blank" rel="noopener">Explore '+id+' at full size <span>↗</span></a><p class="tradeoff">'+trade+'</p>';gallery.append(card)}
const select=document.querySelector('#board-stage');select.innerHTML=stages.map(([v,t])=>'<option value="'+v+'">'+t+'</option>').join('');
function broadcast(reset=false){for(const frame of document.querySelectorAll('iframe'))frame.contentWindow.postMessage({type:'workshop-control',theme,stage,reset},location.origin);for(const a of document.querySelectorAll('.open-direction')){const u=new URL(a.href);u.searchParams.set('stage',stage);u.searchParams.set('theme',theme);a.href=u.href}document.documentElement.dataset.theme=theme;document.querySelector('#board-theme').textContent=theme==='light'?'Switch to Dark':'Switch to Light';document.querySelector('#board-theme').setAttribute('aria-pressed',String(theme==='dark'))}
select.onchange=()=>{stage=select.value;broadcast()};document.querySelector('#board-theme').onclick=()=>{theme=theme==='light'?'dark':'light';broadcast()};document.querySelector('#board-reset').onclick=()=>{stage='fresh';theme='light';select.value=stage;broadcast(true)};
for(const wrap of document.querySelectorAll('.frame-wrap'))new ResizeObserver(()=>{const scale=wrap.clientWidth/1100;wrap.firstElementChild.style.transform='scale('+scale+')';wrap.style.height=(820*scale)+'px'}).observe(wrap);
for(const f of document.querySelectorAll('iframe'))f.addEventListener('load',()=>broadcast());
