export const directions = [
  { id: '01', name: 'Warm Letter', tag: 'Personal & welcoming', description: 'A spacious paper letter with a serif headline and a soft terracotta action. Best for welcoming people; longer for operational messages.', canvas: '#f0ece5', paper: '#fffdf8', ink: '#253b31', muted: '#616b63', border: '#dddcd1', accent: '#aa472c', accentText: '#ffffff', quiet: '#f5f1e8', radius: 4, heading: 'Georgia, serif', size: 36, padding: 38 },
  { id: '02', name: 'Clear Desk', tag: 'Direct & dependable', description: 'A clear white document with a green brand line, a direct headline and a strong action. Best all-purpose base.', canvas: '#edf1ef', paper: '#ffffff', ink: '#153c2c', muted: '#56685e', border: '#dce5df', accent: '#17623f', accentText: '#ffffff', quiet: '#f3f7f4', radius: 12, heading: 'Arial, Helvetica, sans-serif', size: 30, padding: 34 },
  { id: '03', name: 'Commerce Receipt', tag: 'Compact & precise', description: 'A ruled, narrow receipt with a small masthead and compact facts. Easy to scan for internal alerts; more formal for customer mail.', canvas: '#ecebe6', paper: '#fffefa', ink: '#27352f', muted: '#646c64', border: '#d9dcd1', accent: '#234b38', accentText: '#ffffff', quiet: '#f5f4ed', radius: 0, heading: 'Georgia, serif', size: 30, padding: 28 },
  { id: '04', name: 'Market Postcard', tag: 'Confident & memorable', description: 'A deep green title panel, warm citrus accents and generous contrast. Distinctive for milestones; visually louder for frequent codes.', canvas: '#e8eee8', paper: '#ffffff', ink: '#163c2a', muted: '#596c5f', border: '#d7e1d8', accent: '#d9ed9a', accentText: '#163c2a', quiet: '#f2f6ea', radius: 14, heading: 'Arial, Helvetica, sans-serif', size: 34, padding: 32 },
  { id: '05', name: 'Quiet Note', tag: 'Minimal & human', description: 'An unboxed note with a small signature, understated facts and a simple action. Calm and personal; less brand presence in a busy inbox.', canvas: '#ffffff', paper: '#ffffff', ink: '#23352b', muted: '#616e65', border: '#e5e8e4', accent: '#234f38', accentText: '#ffffff', quiet: '#f7f8f5', radius: 0, heading: 'Arial, Helvetica, sans-serif', size: 27, padding: 32 },
  { id: '06', name: 'Warm Desk', tag: 'Recommended combination', description: '02’s clear hierarchy, 01’s warm paper, 03’s ruled facts, 04’s restrained brand accent and 05’s quiet footer.', canvas: '#f0f1eb', paper: '#fffefa', ink: '#183c2b', muted: '#5b685e', border: '#dce2d7', accent: '#1d5d3e', accentText: '#ffffff', quiet: '#f3f5ee', radius: 10, heading: 'Arial, Helvetica, sans-serif', size: 31, padding: 34 },
]

export const defaultPerson = { name: 'Amina Bello', email: 'amina@example.test' }

// Fictional fixtures. Values below do not originate from merchant or provider data.
export function scenarios(person = defaultPerson) {
  return [
    { id: 'waitlist-admin', name: 'Waitlist · internal alert', subject: 'New ewatrade waitlist signup', eyebrow: 'Waitlist / Internal', title: 'A new business joined the waitlist.', intro: 'A visitor joined the EwaTrade waitlist. Keep this record for the next access wave and any relevant operator research.', status: 'New lead', tone: 'neutral', details: [['Lead ID', 'demo-waitlist-1042'], ['Name', person.name], ['Email', person.email]], note: 'No immediate action is required. Keep outreach useful, specific, and easy to opt out of.' },
    { id: 'waitlist-customer', name: 'Waitlist · customer confirmation', subject: 'You are on the ewatrade waitlist', eyebrow: 'Waitlist', title: 'Your place is saved.', intro: `Hi ${person.name}. You are on the EwaTrade waitlist. We will let you know as access opens to more businesses.`, status: 'Place saved', tone: 'success', details: [['Email', person.email]], note: 'We are building one working system for storefronts, orders, stock, fulfillment, and customer communication.' },
    { id: 'approved', name: 'Early access · approved setup', subject: 'Your EwaTrade early access is approved', eyebrow: 'Early access', title: 'Your workspace starts here.', intro: `Hi ${person.name}. Your early access request has been approved. Your private setup link is ready.`, status: 'Access approved', tone: 'success', details: [['Email', person.email], ['Business', 'Amina Home & Trade'], ['Link expires', '9 October 2026, 10:30 UTC']], action: 'Create your workspace', note: 'This link works once and expires automatically. If it expires before setup is complete, request access again with the same email.' },
    { id: 'verification', name: 'Setup · email verification', subject: 'Verify your email to set up EwaTrade', eyebrow: 'Workspace setup', title: 'Verify your email.', intro: `Hi ${person.name}. Confirm your email address before creating your EwaTrade workspace.`, details: [['Email', person.email], ['Expires', '3 October 2026, 10:30 UTC']], action: 'Verify email and continue', note: 'This link expires after 24 hours or when your approved setup link expires. If you did not request this, you can ignore this email.' },
    { id: 'login-code', name: 'Account · sign-in code', subject: 'Your EwaTrade sign-in code', eyebrow: 'Account security', title: 'Your sign-in code.', intro: 'Use the six-digit code below to sign in to your EwaTrade account.', code: '482 619', status: 'Private code', tone: 'attention', note: 'This sample code expires in 10 minutes. EwaTrade will never ask you to send this code by chat, phone, or email.' },
    { id: 'deletion-code', name: 'Account deletion · verification code', subject: 'Your EwaTrade account deletion request code', eyebrow: 'Account security', title: 'Confirm your deletion request.', intro: 'Use this code to verify your account deletion request.', code: '482 619', status: 'Private code', tone: 'attention', note: 'It expires in 10 minutes. If you did not request this, ignore this email. Never share the code.' },
    { id: 'privacy-alert', name: 'Internal · deletion notice alert', subject: '[EwaTrade] 4 unresolved account-deletion notice attempts', eyebrow: 'Operations / Internal', title: 'Deletion notices need review.', intro: 'Inspect the platform-admin account-deletion review queue and provider event history.', status: 'Review needed', tone: 'attention', details: [['Failed notices', '2'], ['Failures after completion', '0'], ['Uncertain sends', '1'], ['Sends in progress over 10 min', '1'], ['Unconfirmed delivery over 1 hr', '0']], note: 'Do not resend an uncertain attempt without reconciling the original provider outcome. This alert contains no person, request, message or recipient identifier.' },
    { id: 'refund-alert', name: 'Internal · Play refund review', subject: '[EwaTrade] 3 unresolved Play refund review cases', eyebrow: 'Operations / Internal', title: 'Refund cases need review.', intro: 'Inspect the platform-admin refund-review queue and follow the reviewed operator procedure.', status: 'Review needed', tone: 'attention', details: [['Unresolved cases', '3'], ['Overdue cases', '1'], ['Earliest deadline (UTC)', '3 October 2026, 16:00']], note: 'A CLAIMED or UNCERTAIN response must be reconciled with Google manually; do not submit it again. This email contains no purchase token, order ID or customer information.' },
    { id: 'store-reply', name: 'Customer · Store reply', subject: 'There is a new reply in your Store conversation', eyebrow: 'Store conversation', title: 'Your Store has replied.', intro: 'There is new activity in your Store conversation. Open EwaTrade to read it.', status: 'New activity', tone: 'success', note: 'For privacy, notification emails never include message content. Open EwaTrade from the same device or account you normally use to read the reply.' },
  ]
}

export function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}

export function renderEmail(direction, message) {
  const d = direction
  const receipt = d.id === '03'
  const postcard = d.id === '04'
  const quiet = d.id === '05'
  const hybrid = d.id === '06'
  const letter = d.id === '01'
  const font = 'Arial, Helvetica, sans-serif'
  const pillColor = message.tone === 'attention' ? '#873f1d' : '#245a3d'
  const pillBackground = message.tone === 'attention' ? '#fbecdf' : '#edf3e7'
  const pad = d.padding
  const hr = `<table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="height:1px;background:${d.border};font-size:0;line-height:0">&nbsp;</td></tr></table>`
  const status = message.status ? `<p style="margin:0 0 22px;font-size:12px;line-height:20px;color:${pillColor}"><span style="display:inline-block;padding:4px 10px;background:${pillBackground};border-radius:${receipt ? 0 : 4}px;font-weight:700">${escapeHtml(message.status)}</span></p>` : ''
  const details = message.details?.length ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;${d.id === '02' || postcard ? `background:${d.quiet};border-radius:6px;` : ''}margin:2px 0 22px;table-layout:fixed">${message.details.map(([label,value], i) => `<tr><td class="detail-label" width="35%" valign="top" style="width:35%;padding:${receipt ? 10 : 13}px ${d.id === '02' || postcard ? 14 : 0}px;border-bottom:1px solid ${d.border};${i === 0 && (receipt || hybrid) ? `border-top:1px solid ${d.border};` : ''}color:${d.muted};font-size:12px;line-height:19px">${escapeHtml(label)}</td><td valign="top" style="padding:${receipt ? 10 : 13}px ${d.id === '02' || postcard ? 14 : 0}px ${receipt ? 10 : 13}px 15px;border-bottom:1px solid ${d.border};${i === 0 && (receipt || hybrid) ? `border-top:1px solid ${d.border};` : ''}font-size:13px;line-height:19px;font-weight:600;color:${d.ink};overflow-wrap:anywhere;word-break:break-word">${escapeHtml(value)}</td></tr>`).join('')}</table>` : ''
  const code = message.code ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:4px 0 24px;background:${postcard ? d.ink : d.quiet};border:1px solid ${d.border};border-radius:${d.radius ? 6 : 0}px"><tr><td style="padding:24px 8px;text-align:center;font-family:Consolas,'Courier New',monospace;font-size:34px;font-weight:700;line-height:42px;letter-spacing:5px;color:${postcard ? '#d9ed9a' : d.ink}">${escapeHtml(message.code)}</td></tr></table>` : ''
  const action = message.action ? `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:6px 0 25px"><tr><td style="border-radius:${d.radius ? 6 : 0}px;background:${d.accent};mso-padding-alt:14px 20px"><a href="#preview-action" style="display:inline-block;padding:14px 20px;font-size:14px;line-height:22px;font-weight:700;color:${d.accentText};text-decoration:none;border-radius:${d.radius ? 6 : 0}px">${escapeHtml(message.action)}${letter || quiet ? '' : '&nbsp; →'}</a></td></tr></table>` : ''
  const eyebrow = `<p style="margin:0 0 14px;font-size:11px;line-height:18px;font-weight:700;letter-spacing:${receipt ? 1.6 : .9}px;text-transform:uppercase;color:${postcard ? '#d9ed9a' : d.muted}">${escapeHtml(message.eyebrow)}</p>`
  const headline = `<h1 style="margin:0 0 ${postcard ? 0 : 20}px;font-family:${d.heading};font-size:${d.size}px;font-weight:${letter || receipt ? 400 : 700};line-height:1.18;letter-spacing:-.65px;color:${postcard ? '#ffffff' : d.ink}">${escapeHtml(message.title)}</h1>`
  let header = `<tr><td class="email-pad" style="padding:28px ${pad}px 24px;border-bottom:1px solid ${d.border}"><table role="presentation" cellspacing="0" cellpadding="0" width="100%"><tr><td style="font-size:20px;font-weight:800;letter-spacing:-.8px;color:${d.ink}">EwaTrade<span style="color:${letter ? d.accent : '#bd773a'}">.</span></td><td align="right" style="font-size:10px;line-height:16px;color:${d.muted}">${letter ? 'Keep commerce in order' : hybrid ? 'COMMERCE, IN ORDER' : 'COMMERCE / OPERATIONS'}</td></tr></table></td></tr>`
  if (quiet) header = `<tr><td class="email-pad" style="padding:34px ${pad}px 16px;font-size:16px;font-weight:700;color:${d.ink}">EwaTrade</td></tr>`
  if (receipt) header = `<tr><td class="email-pad" style="padding:25px ${pad}px 20px;text-align:center;border-bottom:2px solid ${d.ink}"><p style="margin:0 0 6px;font-size:20px;letter-spacing:-.8px;font-weight:800;color:${d.ink}">EwaTrade</p><p style="margin:0;font-size:10px;letter-spacing:1.6px;color:${d.muted}">COMMERCE / OPERATIONS</p></td></tr>`
  if (postcard) header = `<tr><td class="email-pad" style="padding:26px ${pad}px 20px;background:${d.ink};color:#ffffff;font-size:21px;font-weight:800;letter-spacing:-.8px">EwaTrade<span style="color:#d9ed9a">.</span></td></tr>`
  const titleRow = postcard ? `<tr><td class="email-pad" style="padding:10px ${pad}px 30px;background:${d.ink}">${eyebrow}${headline}</td></tr>` : ''
  const topRail = d.id === '02' ? `<tr><td style="height:4px;background:${d.accent};font-size:0;line-height:0">&nbsp;</td></tr>` : hybrid ? `<tr><td style="height:4px;background:#c8d89d;font-size:0;line-height:0">&nbsp;</td></tr>` : ''
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${escapeHtml(message.subject)}</title><style>body{margin:0}a:focus-visible{outline:3px solid #bf6e35;outline-offset:4px} @media(max-width:480px){.outer-pad{padding:16px 10px!important}.email-pad{padding-left:22px!important;padding-right:22px!important}h1{font-size:${Math.min(d.size, 29)}px!important}.detail-label{width:35%!important}.brand-label{display:none!important}} @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}</style></head><body style="margin:0;background:${d.canvas};font-family:${font};color:${d.ink}"><div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all">${escapeHtml(message.intro)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${d.canvas}"><tr><td class="outer-pad" align="center" style="padding:30px 18px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" data-workshop-direction="${d.id}" style="width:100%;max-width:${receipt ? 520 : 600}px;background:${d.paper};border:${quiet ? '0' : `1px solid ${d.border}`};border-radius:${d.radius}px;overflow:hidden">${topRail}${header}${titleRow}<tr><td class="email-pad" style="padding:${postcard ? 28 : quiet ? 22 : 30}px ${pad}px ${quiet ? 16 : 30}px">${postcard ? '' : eyebrow + headline}<p style="margin:0 0 22px;font-size:15px;line-height:25px;color:${d.ink}">${escapeHtml(message.intro)}</p>${status}${code}${details}${action}<p style="margin:0 0 26px;${letter ? `border-left:2px solid ${d.accent};padding-left:14px;` : ''}font-size:12px;line-height:20px;color:${d.muted}">${escapeHtml(message.note)}</p>${quiet ? '' : hr}<p style="margin:20px 0 0;font-size:12px;line-height:20px;color:${d.muted}">Need help? Reply to this email or visit <a href="#preview-help" style="color:${d.ink};text-decoration:underline">ewatrade.com</a>.</p></td></tr>${postcard ? `<tr><td class="email-pad" style="padding:18px ${pad}px;background:${d.quiet};font-size:11px;line-height:18px;color:${d.ink}">EwaTrade · Keep commerce in order.</td></tr>` : receipt ? `<tr><td class="email-pad" style="padding:16px ${pad}px;border-top:1px dashed ${d.border};text-align:center;font-size:11px;line-height:18px;color:${d.muted}">EwaTrade · Keep commerce in order.</td></tr>` : ''}</table>${postcard || receipt ? '' : `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px"><tr><td style="padding:18px 12px;font-size:11px;line-height:18px;${quiet ? 'text-align:left;' : 'text-align:center;'}color:${d.muted}">EwaTrade · Keep commerce in order.</td></tr></table>`}</td></tr></table></body></html>`
}
