"use strict";
const directions=[
{id:"01",name:"Clear Counter",subtitle:"Balanced facts. One obvious next action.",emphasis:"Everyday balance",tradeoff:"A familiar, calm Home. Less immersive than 02, but easier to scan and grow.",why:"The catalog and order facts stay compact. A clear first-order action appears before recent activity, with team setup below.",established:"The first-order prompt becomes New order. Recent records replace the empty state; setup gives way to useful catalog and team shortcuts.",parts:"Compact identity header · next action · two-fact summary · quiet revenue row · recent orders · reusable task rows",recommended:true},
{id:"02",name:"Order First",subtitle:"A focused launchpad for frequent selling.",emphasis:"Fast order creation",tradeoff:"The fastest route into selling. Summary facts and setup carry less visual weight.",why:"A large green action panel creates a clear stopping point. The order button is easy to hit; secondary creation lives in two utility tiles below.",established:"The hero stays stable for daily use. Two recent orders sit below quick actions; adding Products or Services stays in Create.",parts:"Brand action panel · scope-aware totals · two utility tiles · compact activity list"},
{id:"03",name:"Quiet Ledger",subtitle:"Precise, flat and deliberately compact.",emphasis:"Owner’s overview",tradeoff:"Most facts in the least space. More restrained and less welcoming for a brand-new merchant.",why:"A ruled ledger replaces the card stack. Label, value and scope are distinct, with no chart to suggest analytics the controller does not own.",established:"Activity fills the lower ledger. The layout stays stable as orders grow; catalog and team actions remain visible without a task panel.",parts:"Flat header · ruled fact rows · strong primary action · compact utilities · list-led activity"},
{id:"04",name:"Guided Start",subtitle:"A next-step path that grows with the store.",emphasis:"Setup confidence",tradeoff:"Best for getting started. Returning merchants need the compact established mode to avoid repetitive guidance.",why:"The next unfinished step owns the screen. Catalog completion, first order and optional team invitation form a visible sequence; totals remain quiet.",established:"Replace the numbered setup path with an order workspace and optional team action. Completed onboarding stops being the returning merchant’s hero.",parts:"Progress context · vertical task path · expandable current step · quiet totals · adaptive returning workspace"},
{id:"05",name:"Order Desk",subtitle:"Recent orders lead. Details open on demand.",emphasis:"Order review",tradeoff:"Strongest for finding existing work. Revenue scope lives in Store snapshot, making it less glanceable.",why:"Recent orders form the main workspace. Catalog readiness and loaded-order revenue live in a summary disclosure, leaving room for records.",established:"All loaded/Latest changes the visible record slice without changing totals. Tap an order for details or open Store snapshot for facts.",parts:"Order-led title · primary action · local list view · expandable Store snapshot · quiet team utility"}
];
const icons={
home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
order:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 7h6M9 11h6M9 15h4"/>',
catalog:'<path d="m3 8 9-5 9 5v13H3z"/><path d="M7 21V10h10v11M9 14h6M9 17h6"/>',
plus:'<path d="M12 5v14M5 12h14"/>',
more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
search:'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',
sync:'<path d="M20 7a9 9 0 0 0-15-2L3 7M3 3v4h4M4 17a9 9 0 0 0 15 2l2-2M17 17h4v4"/>',
chevron:'<path d="m9 5 7 7-7 7"/>',down:'<path d="m6 9 6 6 6-6"/>',
arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',check:'<path d="m5 12 4 4L19 6"/>',
team:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M16 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 4v3"/>',
wrench:'<path d="M14 6a5 5 0 0 0-7 7L3 17a3 3 0 0 0 4 4l4-4a5 5 0 0 0 7-7l-3 3-4-4z"/>',
signal:'<path d="M4 19v-3M9 19v-7M14 19V8M19 19V4"/>',wifi:'<path d="M3 8a15 15 0 0 1 18 0M6 12a10 10 0 0 1 12 0M9 16a5 5 0 0 1 6 0M12 20h.01"/>',battery:'<rect x="3" y="7" width="16" height="10" rx="2"/><path d="M21 10v4M6 10h10v4H6z"/>'
};
const icon=n=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(icons[n]||icons.order)+'</svg>';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>"R"+(n/100).toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2});
const params=new URLSearchParams(location.search);
const captureMode=params.get("capture")==="1";
document.body.classList.toggle("capture",captureMode);
let theme=params.get("theme")==="dark"?"dark":"light",businessState=["ready","onboarding","established"].includes(params.get("state"))?params.get("state"):"ready",largeText=params.get("text")==="200",favorite=null,selectedDirection=null,modalContext=null;
const states=new Map();
function seed(state){return{ready:state!=="onboarding",orders:state==="established"?[
{id:"S-001",customer:"Sample customer A",totalMinor:45000,label:"Consultation",status:"Recorded"},
{id:"S-002",customer:"Sample customer B",totalMinor:25000,label:"Setup service",status:"Recorded"}]:[],
items:state==="established"?["Consultation","Setup service"]:[],filter:"all",invitePrepared:false,draft:{customer:"",value:""}};}
function resetStates(){directions.forEach(d=>states.set(d.id,seed(businessState)));}
resetStates();
function action(a,label,ic,cls="primary-button",disabled=false){return'<button class="'+cls+'" data-action="'+a+'" '+(disabled?'disabled':'')+'>'+(ic?icon(ic):'')+'<span>'+label+'</span></button>';}
function row(a,label,ic,detail){return'<button class="action-row" data-action="'+a+'"><span class="row-icon">'+icon(ic)+'</span><span>'+label+(detail?'<span class="row-detail">'+detail+'</span>':'')+'</span>'+icon("chevron")+'</button>';}
function header(){return'<header class="phone-header"><button class="avatar" data-action="profile" aria-label="Ishaq profile">I</button><div class="identity"><p class="greeting">Hello, Ishaq</p><button class="business-button" data-action="business" aria-label="Switch Business, Jawdah">Jawdah '+icon("down")+'</button></div><div class="header-tools"><button class="icon-button" data-action="sync" aria-label="Open sync status">'+icon("sync")+'</button><button class="icon-button" data-action="search" aria-label="Open global search">'+icon("search")+'</button></div></header>';}
function sync(){return'<button class="sync-note" data-action="sync">'+icon("check")+'Synced now</button>';}
function cta(s,cls="primary-button"){return s.ready?action("order",s.orders.length?"New order":"Take your first order","plus",cls):action("item","Add a Product or Service","plus",cls);}
function totals(s){return{count:s.orders.length,value:money(s.orders.reduce((n,o)=>n+o.totalMinor,0))};}
function facts(s){const t=totals(s);return'<div class="facts"><div class="fact"><span class="fact-top">'+icon("catalog")+'Catalog</span><strong class="fact-value">'+(s.ready?"Ready":"Not ready")+'</strong></div><div class="fact"><span class="fact-top">'+icon("order")+'Recent orders</span><strong class="fact-value">'+t.count+'</strong></div></div>';}
function revenue(s){const t=totals(s);return'<div class="revenue"><span class="small-label">Recent revenue</span><strong class="fact-value">'+t.value+'</strong><p>'+(s.orders.length?'Across the latest '+s.orders.length+' loaded '+(s.orders.length===1?'order':'orders'):'Across loaded orders')+'</p></div>';}
function ordersHeading(){return'<div class="section-heading"><h3>Recent orders</h3>'+action("orders","See all",null,"text-button")+'</div>';}
function orderRows(s,limit=2){return s.orders.slice(0,limit).map(o=>'<button class="order-row" data-action="order-detail" data-order="'+esc(o.id)+'"><span class="order-avatar">'+esc(o.customer.split(" ").map(x=>x[0]).slice(0,2).join(""))+'</span><span><span class="order-name">'+esc(o.customer)+'</span><span class="order-meta">'+esc(o.id)+' · '+esc(o.label)+'</span></span><span class="order-right">'+money(o.totalMinor)+'<span class="status-label">'+esc(o.status)+'</span></span></button>').join("");}
function empty(s,withAction=false){return'<div class="empty-orders">'+icon("order")+'<strong>No orders yet</strong><p>'+(s.ready?'Your catalog is ready. Your first order will appear here.':'Add a sellable Product or Service, then take your first order.')+'</p>'+(withAction?cta(s):'')+'</div>';}
function ordersBlock(s){return ordersHeading()+(s.orders.length?orderRows(s):empty(s));}
function d01(s){return'<div class="phone-body">'+sync()+'<h2 class="phone-title">'+(s.orders.length?'Your store, at a glance.':s.ready?'Ready for your first order.':'Let’s set up your store.')+'</h2><p class="phone-subtitle">'+(s.orders.length?'Create an order or catch up on recent activity.':s.ready?'Your catalog is ready. Start selling when you are.':'Start with something your customers can buy.')+'</p>'+cta(s)+facts(s)+revenue(s)+ordersBlock(s)+'<div class="section-heading"><h3>'+(s.orders.length?'Store shortcuts':'Keep getting started')+'</h3></div>'+row("catalog",s.ready?"View your catalog":"Add a Product or Service","catalog")+row("team",s.invitePrepared?"Team invite prepared":"Invite your team","team")+'</div>';}
function d02(s){const t=totals(s);return'<section class="action-hero"><p class="phone-kicker">'+(s.ready?'YOUR STORE IS READY':'YOUR NEXT STEP')+'</p><h2 class="phone-title">'+(s.ready?s.orders.length?'Make the next sale.':'Make your first sale.':'Build your catalog.')+'</h2><p class="phone-subtitle">'+(s.ready?'A new order starts right here.':'Add a Product or Service before you take an order.')+'</p>'+cta(s)+'<p class="inline-status">'+icon(s.ready?"check":"catalog")+'Catalog '+(s.ready?'Ready':'not ready')+'</p></section><div class="phone-body">'+sync()+'<div class="sales-snapshot"><div><span class="small-label">Recent orders</span><strong class="fact-value">'+t.count+'</strong></div><div><span class="small-label">Recent revenue</span><strong class="fact-value">'+t.value+'</strong></div></div><p class="scope-info">Across loaded orders · '+t.count+' '+(t.count===1?'order':'orders')+'</p><div class="quick-grid">'+action("item","Add an item","plus","")+action("team",s.invitePrepared?"Invite prepared":"Invite your team","team","")+'</div>'+ordersBlock(s)+'</div>';}
function d03(s){const t=totals(s);return'<div class="phone-body"><div class="ledger-title"><p class="phone-kicker">STORE OVERVIEW</p><h2 class="phone-title">Jawdah</h2>'+sync()+'</div><div class="ledger-line"><span>Catalog</span><strong>'+(s.ready?'Ready':'Not ready')+'</strong></div><div class="ledger-line"><span>Recent orders</span><strong>'+t.count+'</strong></div><div class="ledger-line"><span>Recent revenue</span><strong>'+t.value+'</strong></div><p class="ledger-scope">Across the latest loaded orders.</p>'+cta(s)+row("catalog","Open catalog","catalog")+row("team",s.invitePrepared?"Team invite prepared":"Invite your team","team")+ordersBlock(s)+'</div>';}
function d04(s){const t=totals(s);if(s.orders.length)return'<div class="phone-body">'+sync()+'<div class="guide-label"><p class="phone-kicker">YOUR STORE IS RUNNING</p>'+icon("check")+'</div><h2 class="phone-title">What’s next?</h2><p class="phone-subtitle">Keep your orders moving.</p><div class="guide-step current"><span class="step-number">'+icon("order")+'</span><div class="step-body"><h3 class="step-title">Take another order</h3><p class="step-copy">Your catalog is ready whenever a customer is.</p>'+cta(s)+'</div></div>'+row("team",s.invitePrepared?"Team invite prepared":"Bring your team on board","team","Optional · share the work")+row("catalog","Keep your catalog up to date","catalog")+'<div class="section-heading"><h3>Store snapshot</h3></div><div class="mini-summary"><div><strong>'+t.count+' recent orders</strong><p>Latest loaded records</p></div><div><strong>'+t.value+'</strong><p>Across loaded orders</p></div></div>'+ordersBlock(s)+'</div>';
return'<div class="phone-body">'+sync()+'<div class="guide-label"><p class="phone-kicker">GETTING STARTED</p><div class="guide-progress" aria-label="'+(s.ready?'Catalog step complete':'Catalog step incomplete')+'"><span class="'+(s.ready?'done':'')+'"></span><span></span><span></span></div></div><h2 class="phone-title">'+(s.ready?'You’re ready to sell.':'A store starts with one item.')+'</h2><p class="phone-subtitle">'+(s.ready?'Take your first order, then invite your team when you need a hand.':'Build your catalog, take an order, then bring your team along.')+'</p><div class="guide-path"><div class="guide-step '+(s.ready?'complete':'current')+'"><span class="step-number">'+(s.ready?icon("check"):'1')+'</span><div class="step-body"><h3 class="step-title">'+(s.ready?'Catalog is ready':'Add a Product or Service')+'</h3>'+(s.ready?'<p class="step-copy">You have a sellable item.</p>':'<p class="step-copy">Choose what you sell and set its price.</p>'+action("item","Add your first item","plus"))+'</div></div><div class="guide-step '+(s.ready?'current':'')+'"><span class="step-number">2</span><div class="step-body"><h3 class="step-title">Take your first order</h3><p class="step-copy">'+(s.ready?'Record what your customer is buying.':'Available when your catalog is ready.')+'</p>'+(s.ready?action("order","Create an order","plus"):'')+'</div></div><div class="guide-step"><span class="step-number">3</span><div class="step-body"><h3 class="step-title">'+(s.invitePrepared?'Team invite prepared':'Invite your team')+'</h3><p class="step-copy">Optional · you can do this later.</p>'+action("team","Invite a team member",null,"text-button")+'</div></div></div><div class="mini-summary"><div><strong>0 recent orders</strong><p>Latest loaded records</p></div><div><strong>R0.00</strong><p>Across loaded orders</p></div></div>'+ordersBlock(s)+'</div>';}
function d05(s){const t=totals(s);return'<div class="phone-body">'+sync()+'<div class="desk-top"><h2 class="phone-title">Recent orders</h2><span class="queue-total">'+t.count+'</span></div><p class="scope-info">Latest orders loaded</p><div class="desk-primary">'+cta(s)+'</div><div class="desk-filters" role="group" aria-label="Recent order view"><button data-action="filter-all" aria-pressed="'+(s.filter==="all")+'">All loaded</button><button data-action="filter-latest" aria-pressed="'+(s.filter==="latest")+'">Latest</button>'+action("orders","See all",null,"text-button")+'</div>'+(s.orders.length?orderRows(s,s.filter==="latest"?1:8):empty(s))+'<details class="snapshot-details"><summary>'+icon("catalog")+'Store snapshot '+icon("down")+'</summary><div class="snapshot-inner"><div><span class="small-label">Catalog</span><strong>'+(s.ready?'Ready':'Not ready')+'</strong></div><div><span class="small-label">Recent revenue</span><strong>'+t.value+'</strong></div><p>Across loaded orders · '+t.count+' '+(t.count===1?'order':'orders')+'</p></div></details>'+row("catalog","Open catalog","catalog")+row("team",s.invitePrepared?"Team invite prepared":"Invite your team","team")+'</div>';}
const renderers={"01":d01,"02":d02,"03":d03,"04":d04,"05":d05};
function dock(){return'<nav class="dock" aria-label="Main navigation">'+[["home","Home","home"],["orders","Orders","order"],["create","Create","plus"],["catalog","Products","catalog"],["more","More","more"]].map(([a,label,ic])=>'<button class="nav-button '+(a==="create"?'create':'')+'" data-action="'+a+'" '+(a==="home"?'aria-current="page"':'')+'>'+icon(ic)+'<span>'+label+'</span></button>').join("")+'</nav><div class="android-gesture" aria-hidden="true"></div>';}
function phone(id,t){return'<div class="device d'+id+' '+(largeText?'large-text':'')+'" data-direction="'+id+'" data-theme="'+t+'" aria-label="Direction '+id+', '+t+', Android Home preview"><div class="camera-dot" aria-hidden="true"></div><div class="status-bar" aria-hidden="true"><span>9:18</span><div class="status-symbols">'+icon("signal")+icon("wifi")+icon("battery")+'</div></div><div class="screen-scroll">'+header()+renderers[id](states.get(id))+'</div>'+dock()+'</div>';}
function renderBoard(){document.querySelector("#board").innerHTML=directions.map(d=>'<article class="direction-card" id="card-'+d.id+'"><p class="direction-number">DIRECTION '+d.id+(d.recommended?'<span class="recommend-tag">Recommended</span>':'')+'</p><h2>'+d.name+'</h2><p class="direction-subtitle">'+d.subtitle+'</p><div class="mini-stage">'+phone(d.id,theme)+'</div><div class="card-actions"><a class="review-link" href="#direction-'+d.id+'">Explore '+d.id+' '+icon("arrow")+'</a><button class="star-button" data-favorite="'+d.id+'" aria-label="Favorite direction '+d.id+'" aria-pressed="'+(favorite===d.id)+'">'+(favorite===d.id?'★':'☆')+'</button></div><p class="tradeoff">'+d.tradeoff+'</p></article>').join("");}
function renderDetail(){if(!selectedDirection)return;const d=directions.find(d=>d.id===selectedDirection);document.querySelector("#detail").innerHTML='<div class="detail-heading"><div><p class="eyebrow">DIRECTION '+d.id+' · '+d.emphasis.toUpperCase()+'</p><h2>'+d.name+'</h2></div><a href="#board" class="back-button">← All five directions</a></div><div class="detail-layout"><div class="pair">'+["light","dark"].map(t=>'<div class="full-preview"><p class="theme-preview-label">'+t.toUpperCase()+'<span>390 × 844 · scroll inside phone</span></p>'+phone(d.id,t)+'</div>').join("")+'</div><aside class="detail-notes"><div><h3>What changes</h3><p>'+d.why+'</p><h3>When the business grows</h3><p>'+d.established+'</p></div><div><h3>Tradeoff</h3><p>'+d.tradeoff+'</p><h3>Reusable pieces</h3><p>'+d.parts+'.</p><button class="soft-button" data-favorite="'+d.id+'" aria-pressed="'+(favorite===d.id)+'">'+(favorite===d.id?'★ Favorited':'☆ Favorite this direction')+'</button><p style="font-size:11px;margin-top:10px">A favorite is review feedback; it does not implement the design.</p></div><nav class="detail-nav" aria-label="Other design directions">'+directions.map(x=>'<a href="#direction-'+x.id+'" aria-current="'+(x.id===d.id)+'">'+x.id+'</a>').join("")+'</nav></aside></div>';}
function render(){const positions=new Map([...document.querySelectorAll(".device")].map(d=>[d.dataset.direction+d.dataset.theme,d.querySelector(".screen-scroll").scrollTop]));renderBoard();renderDetail();document.querySelectorAll(".device").forEach(d=>d.querySelector(".screen-scroll").scrollTop=positions.get(d.dataset.direction+d.dataset.theme)||0);document.querySelectorAll("[data-theme]:not(.device):not(dialog)").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.theme===theme)));document.querySelector("#text-control").setAttribute("aria-pressed",String(largeText));document.querySelector("#text-control").textContent=largeText?"200% → 100%":"100% → 200%";document.querySelector("#state-control").value=businessState;document.querySelector("#sample-note").textContent=businessState==="established"?"LOCAL FIXTURE: two sample orders (R450.00 + R250.00 = R700.00), catalog ready. These are illustrative records, not Jawdah’s production data. Each direction has isolated local state.":businessState==="onboarding"?"LOCAL ONBOARDING FIXTURE: catalog not ready, 0 recent orders, R0.00. Add an item to unlock first-order creation. Each direction has isolated local state.":"Observed reference facts: Jawdah · Catalog Ready · 0 recent orders · R0.00 across loaded orders. Preview edits are local and isolated per direction.";}
function route(){const m=location.hash.match(/^#direction-(0[1-5])$/);selectedDirection=m?m[1]:null;document.querySelector("#board").hidden=!!selectedDirection;document.querySelector("#detail").hidden=!selectedDirection;render();if(m)document.querySelector("#detail").scrollIntoView({block:"start"});}
function announce(message){document.querySelector("#announcement").textContent=message;}
function showDialog(title,content){const dialog=document.querySelector("#preview-dialog");dialog.dataset.theme=modalContext?.theme||theme;document.querySelector("#dialog-context").textContent="DIRECTION "+(modalContext?.id||"")+" · LOCAL PREVIEW";document.querySelector("#dialog-body").innerHTML='<h2 id="dialog-title">'+title+'</h2>'+content;if(!dialog.open)dialog.showModal();const field=dialog.querySelector("input");if(field)field.focus();else dialog.querySelector("#close-dialog").focus();}
function openOrder(){const s=states.get(modalContext.id);if(!s.ready){showDialog("Add an item first",'<p>Your catalog needs a sellable Product or Service before you can create an order.</p>'+action("item","Add an item","plus"));return;}showDialog("Create an order",'<p>Try a simple order to see this direction move from empty to active.</p><form id="order-form"><label for="sample-customer">Customer name</label><input id="sample-customer" name="customer" required maxlength="80" autocomplete="off" value="'+esc(s.draft.customer)+'" placeholder="Sample customer"><label for="sample-value">Order value (R)</label><input id="sample-value" name="value" required inputmode="decimal" autocomplete="off" value="'+esc(s.draft.value)+'" placeholder="250.00"><p class="form-error" id="order-error" role="alert"></p><button type="submit" class="primary-button">'+icon("check")+'Create preview order</button></form>');}
function openItem(){showDialog("Add a catalog item",'<p>This simplified local interaction marks the catalog ready. The native Product and Service editors stay unchanged.</p><form id="item-form"><label for="sample-item">Item name</label><input id="sample-item" name="item" required maxlength="100" autocomplete="off" placeholder="Sample Product or Service"><button type="submit" class="primary-button">'+icon("check")+'Add preview item</button></form>');}
function openOrders(){const s=states.get(modalContext.id);showDialog("Recent orders",'<p>'+s.orders.length+' loaded '+(s.orders.length===1?'order':'orders')+' · '+totals(s).value+' total value</p>'+(s.orders.length?orderRows(s,8):empty(s,true)));}
function handleAction(name,element){const s=states.get(modalContext.id);switch(name){
case"order":openOrder();break;case"item":openItem();break;
case"create":showDialog("Create",'<p>Choose what you want to add to Jawdah.</p>'+row("order","Order","order",s.ready?"Record a customer order":"Add a sellable item first")+row("item","Product or Service","catalog","Add something your customers can buy")+row("team","Staff invitation","team","Prepare a team invitation"));break;
case"catalog":if(!s.ready){openItem();break;}showDialog("Your catalog",'<p>Catalog Ready · a sellable item is available.</p>'+(s.items.length?s.items.map(i=>'<p><b>'+esc(i)+'</b></p>').join(""):'<p>The reference capture does not provide item names.</p>')+action("item","Add a Product or Service","plus"));break;
case"orders":openOrders();break;
case"order-detail":{const o=s.orders.find(o=>o.id===element.dataset.order);if(o)showDialog("Order "+esc(o.id),'<p><b>'+esc(o.customer)+'</b></p><p>'+esc(o.label)+' · '+esc(o.status)+'</p><div class="ledger-line"><span>Order value</span><strong>'+money(o.totalMinor)+'</strong></div><p style="margin-top:14px">This order contributes to Recent revenue across loaded orders.</p>');break;}
case"team":showDialog("Invite your team",'<p>Prepare a sample invitation to see the local setup acknowledgement.</p><form id="team-form"><label for="sample-team">Team member name</label><input id="sample-team" name="member" required maxlength="80" autocomplete="off" placeholder="Sample team member"><button class="primary-button" type="submit">Prepare preview invitation</button></form>');break;
case"sync":showDialog("Sync status",'<p>Synced now</p><div class="ledger-line"><span>Waiting to sync</span><strong>0</strong></div><p style="margin-top:14px">The reference is a connected Home. Production must preserve distinct queued-order and loaded-order-value semantics.</p>');break;
case"search":showDialog("Search Jawdah",'<label for="sample-search">Search local orders and items</label><input id="sample-search" autocomplete="off" placeholder="Customer, order or item"><div id="search-results"><p style="margin-top:15px">Enter a name to search this direction’s local records.</p></div>');break;
case"business":showDialog("Switch Business",'<p>Your current business</p>'+row("home","Jawdah","check","Currently selected"));break;
case"profile":showDialog("Ishaq",'<p>QA Owner · Jawdah</p><p>The preview preserves identity from the saved Home capture.</p>');break;
case"more":showDialog("More",row("team","Invite your team","team")+row("sync","Sync status","sync")+row("business","Switch Business","catalog"));break;
case"home":document.querySelector("#preview-dialog").close();announce("Home preview");break;
case"filter-all":case"filter-latest":s.filter=name==="filter-all"?"all":"latest";render();announce("Showing "+(s.filter==="all"?"all loaded orders":"latest loaded order"));break;
}}
document.addEventListener("click",event=>{const button=event.target.closest("button,[data-action]");if(!button)return;if(button.dataset.favorite){favorite=favorite===button.dataset.favorite?null:button.dataset.favorite;render();announce(favorite?"Direction "+favorite+" favorited for review. No implementation selected.":"Favorite cleared");return;}if(button.dataset.theme){theme=button.dataset.theme;render();return;}if(button.id==="text-control"){largeText=!largeText;render();return;}if(button.id==="reset-control"){document.querySelector("#preview-dialog").close();businessState="ready";theme="light";largeText=false;favorite=null;resetStates();document.querySelectorAll(".screen-scroll").forEach(e=>e.scrollTop=0);render();announce("All previews, drafts, favorites and controls reset.");return;}if(button.id==="close-dialog"){document.querySelector("#preview-dialog").close();return;}if(button.dataset.action){const device=button.closest(".device");if(device)modalContext={id:device.dataset.direction,theme:device.dataset.theme,action:button.dataset.action};if(modalContext)handleAction(button.dataset.action,button);}});
document.querySelector("#state-control").addEventListener("change",e=>{businessState=e.target.value;document.querySelector("#preview-dialog").close();resetStates();document.querySelectorAll(".screen-scroll").forEach(e=>e.scrollTop=0);render();announce("Business state updated for all five directions.");});
document.addEventListener("input",e=>{if(!modalContext)return;const s=states.get(modalContext.id);if(e.target.id==="sample-customer")s.draft.customer=e.target.value;if(e.target.id==="sample-value")s.draft.value=e.target.value;if(e.target.id==="sample-search"){const q=e.target.value.trim().toLowerCase();const found=s.orders.filter(o=>(o.id+" "+o.customer+" "+o.label).toLowerCase().includes(q));const items=s.items.filter(i=>i.toLowerCase().includes(q));document.querySelector("#search-results").innerHTML=q?(found.length||items.length?orderRows({...s,orders:found},8)+items.map(i=>'<p style="margin-top:12px">'+esc(i)+'</p>').join(""):'<p style="margin-top:15px">No matching local records.</p>'):'<p style="margin-top:15px">Enter a name to search this direction’s local records.</p>';}});
document.addEventListener("submit",event=>{if(!event.target.matches("#order-form,#item-form,#team-form"))return;event.preventDefault();const s=states.get(modalContext.id),data=new FormData(event.target);if(event.target.id==="order-form"){const value=String(data.get("value")).trim(),customer=String(data.get("customer")).trim();if(!customer||!/^\d{1,7}(\.\d{1,2})?$/.test(value)||Number(value)<=0){document.querySelector("#order-error").textContent="Enter a customer and a positive value with up to two decimal places.";return;}const[whole,fraction=""]=value.split(".");const minor=Number(whole)*100+Number(fraction.padEnd(2,"0"));s.sequence=(s.sequence||0)+1;s.orders.unshift({id:"P-"+String(s.sequence).padStart(3,"0"),customer,totalMinor:minor,label:s.items[0]||"Catalog item",status:"Recorded"});s.orders=s.orders.slice(0,8);s.draft={customer:"",value:""};announce("Preview order created. Count and loaded-order revenue updated for this direction.");}else if(event.target.id==="item-form"){const item=String(data.get("item")).trim();if(!item)return;s.items.push(item);s.ready=true;announce("Preview catalog ready. Order creation unlocked for this direction.");}else{const member=String(data.get("member")).trim();if(!member)return;s.invitePrepared=true;showDialog("Invitation prepared",'<p>A local invitation draft for <b>'+esc(member)+'</b> is ready.</p><p>No invitation was sent.</p>');render();return;}document.querySelector("#preview-dialog").close();render();});
document.querySelector("#preview-dialog").addEventListener("close",()=>{if(modalContext){const device=[...document.querySelectorAll(".device")].find(d=>d.dataset.direction===modalContext.id&&d.dataset.theme===modalContext.theme&&!d.closest("[hidden]"));device?.querySelector('[data-action="'+modalContext.action+'"]')?.focus({preventScroll:true});}});
window.addEventListener("hashchange",route);
route();
